PROMPT Instalando consulta inicial de Catastro

@@SP_CAT_INM_GET_ALL.sql
@@SP_CAT_INM_GET_ID.sql
@@SP_CAT_INM_GET_REL.sql

SHOW ERRORS PROCEDURE SP_CAT_INM_GET_ALL
SHOW ERRORS PROCEDURE SP_CAT_INM_GET_ID
SHOW ERRORS PROCEDURE SP_CAT_INM_GET_REL
