CREATE OR REPLACE PROCEDURE SP_CAT_INM_GET_REL
(
  p_CodigoInmueble IN NUMBER,
  p_CodigoEmpresa  IN NUMBER,
  p_Caracteristicas OUT SYS_REFCURSOR,
  p_Documentos      OUT SYS_REFCURSOR,
  p_Folios          OUT SYS_REFCURSOR,
  p_OtrosDatos      OUT SYS_REFCURSOR,
  p_Roles           OUT SYS_REFCURSOR,
  p_Usos            OUT SYS_REFCURSOR,
  p_Multiusos       OUT SYS_REFCURSOR,
  p_Message         OUT VARCHAR2
)
AS
  v_CodigoFicha        NUMBER;
  v_CodigoContribuyente NUMBER;
  v_Count               NUMBER;
BEGIN
  SELECT COUNT(*), MAX(CODIGO_FICHA), MAX(CODIGO_CONTRIBUYENTE)
    INTO v_Count, v_CodigoFicha, v_CodigoContribuyente
    FROM CAT_INMUEBLES
   WHERE CODIGO_INMUEBLE = p_CodigoInmueble
     AND CODIGO_EMPRESA = p_CodigoEmpresa;

  IF v_Count = 0 THEN
    p_Message := 'No se encontró el inmueble solicitado.';
  ELSE
    p_Message := 'success';
  END IF;

  OPEN p_Caracteristicas FOR
    SELECT CODIGO_PADRE, CODIGO_DESC, CODIGO_CHE
      FROM CAT_CARAC_INM
     WHERE CODIGO_INMUEBLE = p_CodigoInmueble
     ORDER BY CODIGO_PADRE, CODIGO_DESC;

  OPEN p_Documentos FOR
    SELECT CODIGO_DOCUMENTOS_LEGALES, DOCUMENTO_NUMERO, FOLIO_NUMERO,
           TOMO_NUMERO, PROF_NUMERO, FECHA_REGISTRO, AREA_TERRENO,
           PRECIO_TERRENO
      FROM CAT_DOCUMENTOS_LEGALES
     WHERE CODIGO_FICHA = v_CodigoFicha
       AND CODIGO_EMPRESA = p_CodigoEmpresa
     ORDER BY CODIGO_DOCUMENTOS_LEGALES;

  OPEN p_Folios FOR
    SELECT OFICINA_REG, ESTADO, MUNICIPIO, PARROQUIA,
           NUMERO_INSCRIPCION, FECHA, VALOR_ADQUISICION,
           ASIENTOREGISTRAL
      FROM CAT_FOLIO_REAL
     WHERE CODIGO_INMUEBLE = p_CodigoInmueble
       AND CODIGO_CONTRIBUYENTE = v_CodigoContribuyente
     ORDER BY FECHA DESC, NUMERO_INSCRIPCION;

  OPEN p_OtrosDatos FOR
    SELECT NUMERO_TRAMITE, FECHA_RECEPCION, ELABORADO_POR,
           FECHA_ELABORACION, TIPO_TRAMITE
      FROM CAT_OTROS_DATOS
     WHERE CODIGO_INMUEBLE = p_CodigoInmueble
       AND CODIGO_CONTRIBUYENTE = v_CodigoContribuyente
     ORDER BY FECHA_RECEPCION DESC, NUMERO_TRAMITE;

  OPEN p_Roles FOR
    SELECT CODIGO_ROL, CODIGO_CONTACTO, ROL_ID, FECHA_INI, FECHA_FIN,
           CODIGO_CONTRIBUYENTE, NACIONALIDAD_ID
      FROM CAT_ROLES
     WHERE CODIGO_INMUEBLE = p_CodigoInmueble
       AND CODIGO_EMPRESA = p_CodigoEmpresa
     ORDER BY FECHA_INI DESC, CODIGO_ROL;

  OPEN p_Usos FOR
    SELECT CODIGO_USO, ZONIFICACION, PRINCIPAL, FECHA_INS
      FROM CAT_USO_ZONI
     WHERE CODIGO_INMUEBLE = p_CodigoInmueble
       AND CODIGO_CONTRIBUYENTE = v_CodigoContribuyente
       AND CODIGO_EMPRESA = p_CodigoEmpresa
     ORDER BY PRINCIPAL DESC, CODIGO_USO;

  OPEN p_Multiusos FOR
    SELECT m.CODIGO_DIRECCION, m.TIPO, m.TIPO_UNIDAD, m.METROS
      FROM CAT_MULITUSO m
     WHERE m.CODIGO_INMUEBLE = p_CodigoInmueble
       AND m.CODIGO_CONTRIBUYENTE = v_CodigoContribuyente
       AND EXISTS
           (SELECT 1
              FROM CAT_DIRECCIONES d
             WHERE d.CODIGO_DIRECCION = m.CODIGO_DIRECCION
               AND d.CODIGO_EMPRESA = p_CodigoEmpresa)
     ORDER BY m.CODIGO_DIRECCION, m.TIPO, m.TIPO_UNIDAD;
END SP_CAT_INM_GET_REL;
/
