CREATE OR REPLACE PROCEDURE SP_CAT_MULTAS_GET_INM
(p_CodigoInmueble IN NUMBER, p_CodigoContribuyente IN NUMBER,
 p_CodigoEmpresa IN NUMBER, p_ResultSet OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT m.CODIGO_MULTA, m.CODIGO_DOCUMENTOS_LEGALES, m.MONTO,
           m.FECHA, m.FECHA_REGISTRO, m.CODIGO_FICHA
      FROM CAT_MULTAS m
     WHERE m.CODIGO_INMUEBLE = p_CodigoInmueble
       AND m.CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
       AND EXISTS (SELECT 1 FROM CAT_INMUEBLES i
                    WHERE i.CODIGO_INMUEBLE = m.CODIGO_INMUEBLE
                      AND i.CODIGO_CONTRIBUYENTE = m.CODIGO_CONTRIBUYENTE
                      AND i.CODIGO_EMPRESA = p_CodigoEmpresa)
     ORDER BY m.FECHA_REGISTRO DESC, m.CODIGO_MULTA DESC;
END SP_CAT_MULTAS_GET_INM;
/
