CREATE OR REPLACE PROCEDURE ADM.SP_REP_COMP_IVA_DOC_GET (
    p_CodigoOrdenPago IN NUMBER,
    p_ResultSet       OUT SYS_REFCURSOR,
    p_Message         OUT VARCHAR2,
    p_TotalRecords    OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
      INTO p_TotalRecords
      FROM ADM.ADM_DOCUMENTOS_OP DOC
     WHERE DOC.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    OPEN p_ResultSet FOR
        SELECT
            ROW_NUMBER() OVER (ORDER BY DOC.CODIGO_DOCUMENTO_OP) NUMERO_OPERACION,
            DOC.FECHA_DOCUMENTO FECHA_FACTURA,
            NVL(DOC.NUMERO_DOCUMENTO, '') NUMERO_FACTURA,
            NVL(DOC.NUMERO_CONTROL_DOCUMENTO, '00-00000000') NUMERO_CONTROL_FACTURA,
            NVL(TDOC.EXTRA2, '') NUMERO_NOTA_DEBITO,
            NVL(TDOC.EXTRA3, '') NUMERO_NOTA_CREDITO,
            NVL(TDOC.EXTRA1, '') TIPO_TRANSACCION,
            NVL(DOC.NUMERO_DOCUMENTO_AFECTADO, '') NUMERO_FACTURA_AFECTADA,
            NVL(DOC.MONTO_DOCUMENTO, 0) TOTAL_COMPRAS_IVA,
            NVL(DOC.MONTO_IMPUESTO_EXENTO, 0) COMPRAS_SIN_CREDITO,
            NVL(DOC.BASE_IMPONIBLE, 0) BASE_IMPONIBLE,
            NVL(TIMP.EXTRA1, '') ALICUOTA,
            NVL(DOC.MONTO_IMPUESTO, 0) IMPUESTO_IVA,
            NVL(DOC.MONTO_RETENIDO, 0) IVA_RETENIDO
          FROM ADM.ADM_DOCUMENTOS_OP DOC
          LEFT JOIN ADM.ADM_DESCRIPTIVAS TDOC
            ON TDOC.DESCRIPCION_ID = DOC.TIPO_DOCUMENTO_ID
          LEFT JOIN ADM.ADM_DESCRIPTIVAS TIMP
            ON TIMP.DESCRIPCION_ID = DOC.TIPO_IMPUESTO_ID
         WHERE DOC.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago
         ORDER BY DOC.CODIGO_DOCUMENTO_OP;

    p_Message := 'Success';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
        p_TotalRecords := 0;
        OPEN p_ResultSet FOR
            SELECT
                CAST(NULL AS NUMBER) NUMERO_OPERACION,
                CAST(NULL AS DATE) FECHA_FACTURA,
                CAST(NULL AS VARCHAR2(100)) NUMERO_FACTURA,
                CAST(NULL AS VARCHAR2(100)) NUMERO_CONTROL_FACTURA,
                CAST(NULL AS VARCHAR2(100)) NUMERO_NOTA_DEBITO,
                CAST(NULL AS VARCHAR2(100)) NUMERO_NOTA_CREDITO,
                CAST(NULL AS VARCHAR2(100)) TIPO_TRANSACCION,
                CAST(NULL AS VARCHAR2(100)) NUMERO_FACTURA_AFECTADA,
                CAST(NULL AS NUMBER) TOTAL_COMPRAS_IVA,
                CAST(NULL AS NUMBER) COMPRAS_SIN_CREDITO,
                CAST(NULL AS NUMBER) BASE_IMPONIBLE,
                CAST(NULL AS VARCHAR2(100)) ALICUOTA,
                CAST(NULL AS NUMBER) IMPUESTO_IVA,
                CAST(NULL AS NUMBER) IVA_RETENIDO
              FROM DUAL
             WHERE 1 = 0;
END SP_REP_COMP_IVA_DOC_GET;
/
