PROMPT Creando tablas SIS Seguridad normalizada

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_MOD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_MOD (
        CODIGO_MOD NUMBER(10,0) NOT NULL,
        CODIGO VARCHAR2(10) NOT NULL,
        NOMBRE VARCHAR2(100) NOT NULL,
        ICONO VARCHAR2(100),
        ORDEN NUMBER(10,0) DEFAULT 0 NOT NULL,
        ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL,
        USUARIO_UPD NUMBER(10,0),
        FECHA_UPD DATE
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_MENU';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_MENU (
        CODIGO_MENU NUMBER(10,0) NOT NULL,
        CODIGO_MOD NUMBER(10,0) NOT NULL,
        CODIGO_PADRE NUMBER(10,0),
        TITULO VARCHAR2(120) NOT NULL,
        PATH VARCHAR2(300),
        ICONO VARCHAR2(100),
        ORDEN NUMBER(10,0) DEFAULT 0 NOT NULL,
        ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL,
        USUARIO_UPD NUMBER(10,0),
        FECHA_UPD DATE
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_PERM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_PERM (
        CODIGO_PERM NUMBER(10,0) NOT NULL,
        CODIGO_MOD NUMBER(10,0) NOT NULL,
        CLAVE VARCHAR2(120) NOT NULL,
        NOMBRE VARCHAR2(120) NOT NULL,
        DESCRIPCION VARCHAR2(300),
        ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL,
        USUARIO_UPD NUMBER(10,0),
        FECHA_UPD DATE
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_MENU_PERM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_MENU_PERM (
        CODIGO_MENU NUMBER(10,0) NOT NULL,
        CODIGO_PERM NUMBER(10,0) NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_ROL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_ROL (
        CODIGO_ROL NUMBER(10,0) NOT NULL,
        CODIGO_MOD NUMBER(10,0) NOT NULL,
        CLAVE VARCHAR2(60) NOT NULL,
        NOMBRE VARCHAR2(120) NOT NULL,
        DESCRIPCION VARCHAR2(300),
        ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL,
        USUARIO_UPD NUMBER(10,0),
        FECHA_UPD DATE
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_ROL_MENU';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_ROL_MENU (
        CODIGO_ROL NUMBER(10,0) NOT NULL,
        CODIGO_MENU NUMBER(10,0) NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_ROL_PERM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_ROL_PERM (
        CODIGO_ROL NUMBER(10,0) NOT NULL,
        CODIGO_PERM NUMBER(10,0) NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_USR_ROL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_USR_ROL (
        CODIGO_USR_ROL NUMBER(10,0) NOT NULL,
        CODIGO_USUARIO NUMBER(10,0) NOT NULL,
        CODIGO_ROL NUMBER(10,0) NOT NULL,
        CODIGO_EMPRESA NUMBER(10,0) NOT NULL,
        ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL,
        USUARIO_UPD NUMBER(10,0),
        FECHA_UPD DATE
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_USR_PERM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_USR_PERM (
        CODIGO_USR_PERM NUMBER(10,0) NOT NULL,
        CODIGO_USUARIO NUMBER(10,0) NOT NULL,
        CODIGO_PERM NUMBER(10,0) NOT NULL,
        CODIGO_EMPRESA NUMBER(10,0) NOT NULL,
        TIPO VARCHAR2(5) NOT NULL,
        ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL,
        USUARIO_INS NUMBER(10,0),
        FECHA_INS DATE DEFAULT SYSDATE NOT NULL,
        USUARIO_UPD NUMBER(10,0),
        FECHA_UPD DATE
      )';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'OSS_SEG_AUD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE OSS_SEG_AUD (
        CODIGO_AUD NUMBER(10,0) NOT NULL,
        CODIGO_USUARIO NUMBER(10,0),
        CODIGO_EMPRESA NUMBER(10,0),
        ACCION VARCHAR2(50) NOT NULL,
        DETALLE VARCHAR2(1000),
        USUARIO_ACCION NUMBER(10,0),
        FECHA_ACCION DATE DEFAULT SYSDATE NOT NULL
      )';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_MOD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MOD ADD CONSTRAINT PK_OSS_MOD PRIMARY KEY (CODIGO_MOD)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'UQ_OSS_MOD_COD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MOD ADD CONSTRAINT UQ_OSS_MOD_COD UNIQUE (CODIGO)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_MENU';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MENU ADD CONSTRAINT PK_OSS_MENU PRIMARY KEY (CODIGO_MENU)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_MENU_MOD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MENU ADD CONSTRAINT FK_OSS_MENU_MOD FOREIGN KEY (CODIGO_MOD) REFERENCES OSS_MOD (CODIGO_MOD)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_MENU_PAD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MENU ADD CONSTRAINT FK_OSS_MENU_PAD FOREIGN KEY (CODIGO_PADRE) REFERENCES OSS_MENU (CODIGO_MENU)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_PERM ADD CONSTRAINT PK_OSS_PERM PRIMARY KEY (CODIGO_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'UQ_OSS_PERM_CLV';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_PERM ADD CONSTRAINT UQ_OSS_PERM_CLV UNIQUE (CLAVE)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_PERM_MOD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_PERM ADD CONSTRAINT FK_OSS_PERM_MOD FOREIGN KEY (CODIGO_MOD) REFERENCES OSS_MOD (CODIGO_MOD)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_MENU_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MENU_PERM ADD CONSTRAINT PK_OSS_MENU_PERM PRIMARY KEY (CODIGO_MENU, CODIGO_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_MPERM_MENU';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MENU_PERM ADD CONSTRAINT FK_OSS_MPERM_MENU FOREIGN KEY (CODIGO_MENU) REFERENCES OSS_MENU (CODIGO_MENU)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_MPERM_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_MENU_PERM ADD CONSTRAINT FK_OSS_MPERM_PERM FOREIGN KEY (CODIGO_PERM) REFERENCES OSS_PERM (CODIGO_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_ROL';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL ADD CONSTRAINT PK_OSS_ROL PRIMARY KEY (CODIGO_ROL)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'UQ_OSS_ROL_CLV';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL ADD CONSTRAINT UQ_OSS_ROL_CLV UNIQUE (CLAVE)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_ROL_MOD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL ADD CONSTRAINT FK_OSS_ROL_MOD FOREIGN KEY (CODIGO_MOD) REFERENCES OSS_MOD (CODIGO_MOD)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_ROL_MENU';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL_MENU ADD CONSTRAINT PK_OSS_ROL_MENU PRIMARY KEY (CODIGO_ROL, CODIGO_MENU)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_RMENU_ROL';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL_MENU ADD CONSTRAINT FK_OSS_RMENU_ROL FOREIGN KEY (CODIGO_ROL) REFERENCES OSS_ROL (CODIGO_ROL)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_RMENU_MENU';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL_MENU ADD CONSTRAINT FK_OSS_RMENU_MENU FOREIGN KEY (CODIGO_MENU) REFERENCES OSS_MENU (CODIGO_MENU)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_ROL_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL_PERM ADD CONSTRAINT PK_OSS_ROL_PERM PRIMARY KEY (CODIGO_ROL, CODIGO_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_RPERM_ROL';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL_PERM ADD CONSTRAINT FK_OSS_RPERM_ROL FOREIGN KEY (CODIGO_ROL) REFERENCES OSS_ROL (CODIGO_ROL)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_RPERM_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_ROL_PERM ADD CONSTRAINT FK_OSS_RPERM_PERM FOREIGN KEY (CODIGO_PERM) REFERENCES OSS_PERM (CODIGO_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_USR_ROL';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_USR_ROL ADD CONSTRAINT PK_OSS_USR_ROL PRIMARY KEY (CODIGO_USR_ROL)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'UQ_OSS_USR_ROL';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_USR_ROL ADD CONSTRAINT UQ_OSS_USR_ROL UNIQUE (CODIGO_USUARIO, CODIGO_ROL, CODIGO_EMPRESA)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_UROL_ROL';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_USR_ROL ADD CONSTRAINT FK_OSS_UROL_ROL FOREIGN KEY (CODIGO_ROL) REFERENCES OSS_ROL (CODIGO_ROL)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_USR_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_USR_PERM ADD CONSTRAINT PK_OSS_USR_PERM PRIMARY KEY (CODIGO_USR_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'UQ_OSS_USR_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_USR_PERM ADD CONSTRAINT UQ_OSS_USR_PERM UNIQUE (CODIGO_USUARIO, CODIGO_PERM, CODIGO_EMPRESA)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'CK_OSS_UPERM_TIPO';
  IF v_count = 0 THEN EXECUTE IMMEDIATE q'[ALTER TABLE OSS_USR_PERM ADD CONSTRAINT CK_OSS_UPERM_TIPO CHECK (TIPO IN ('ALLOW', 'DENY'))]'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_OSS_UPERM_PERM';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_USR_PERM ADD CONSTRAINT FK_OSS_UPERM_PERM FOREIGN KEY (CODIGO_PERM) REFERENCES OSS_PERM (CODIGO_PERM)'; END IF;

  SELECT COUNT(1) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_OSS_SEG_AUD';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE OSS_SEG_AUD ADD CONSTRAINT PK_OSS_SEG_AUD PRIMARY KEY (CODIGO_AUD)'; END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_dups NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_indexes WHERE index_name = 'IDX_OSS_USR_ROL_U01';
  IF v_count = 0 THEN
    SELECT COUNT(1)
      INTO v_dups
      FROM (
        SELECT CODIGO_USUARIO, UPPER(TRIM(DESCRIPCION)) DESCRIPCION
          FROM OSS_USUARIO_ROL
         GROUP BY CODIGO_USUARIO, UPPER(TRIM(DESCRIPCION))
        HAVING COUNT(1) > 1
      );

    IF v_dups = 0 THEN
      EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_OSS_USR_ROL_U01 ON OSS_USUARIO_ROL (CODIGO_USUARIO, UPPER(TRIM(DESCRIPCION)))';
    END IF;
  END IF;
END;
/

PROMPT Tablas SIS Seguridad normalizada listas
