PROMPT Rollback SIS Seguridad
PROMPT Reemplace __SUFIJO__ por el sufijo generado por 04_BACKUP_SIS_SEG.sql

/*
DECLARE
BEGIN
  DELETE FROM OSS_USR_PERM;
  INSERT INTO OSS_USR_PERM SELECT * FROM B_OSS_NUPERM___SUFIJO__;

  DELETE FROM OSS_USR_ROL;
  INSERT INTO OSS_USR_ROL SELECT * FROM B_OSS_NUROL___SUFIJO__;

  DELETE FROM OSS_USUARIO_ROL;
  INSERT INTO OSS_USUARIO_ROL SELECT * FROM B_OSS_UROL___SUFIJO__;

  COMMIT;
END;
/
*/

PROMPT Rollback SIS Seguridad preparado
