PROMPT Validando seguridad del modulo Soporte

PROMPT Tablas requeridas
SELECT req.TABLE_NAME,
       CASE WHEN obj.TABLE_NAME IS NULL THEN 'FALTA' ELSE 'OK' END ESTADO
  FROM (
        SELECT 'OSS_MOD' TABLE_NAME FROM dual UNION ALL
        SELECT 'OSS_MENU' FROM dual UNION ALL
        SELECT 'OSS_MENU_PERM' FROM dual UNION ALL
        SELECT 'OSS_PERM' FROM dual UNION ALL
        SELECT 'OSS_ROL' FROM dual UNION ALL
        SELECT 'OSS_ROL_MENU' FROM dual UNION ALL
        SELECT 'OSS_ROL_PERM' FROM dual UNION ALL
        SELECT 'OSS_SEG_AUD' FROM dual UNION ALL
        SELECT 'OSS_USR_PERM' FROM dual UNION ALL
        SELECT 'OSS_USR_ROL' FROM dual UNION ALL
        SELECT 'OSS_USUARIO_ROL' FROM dual
       ) req
  LEFT JOIN USER_TABLES obj ON obj.TABLE_NAME = req.TABLE_NAME
 ORDER BY req.TABLE_NAME;

PROMPT Resumen de faltantes
SELECT COUNT(*) FALTANTES
  FROM (
        SELECT 'OSS_MOD' TABLE_NAME FROM dual UNION ALL
        SELECT 'OSS_MENU' FROM dual UNION ALL
        SELECT 'OSS_MENU_PERM' FROM dual UNION ALL
        SELECT 'OSS_PERM' FROM dual UNION ALL
        SELECT 'OSS_ROL' FROM dual UNION ALL
        SELECT 'OSS_ROL_MENU' FROM dual UNION ALL
        SELECT 'OSS_ROL_PERM' FROM dual UNION ALL
        SELECT 'OSS_SEG_AUD' FROM dual UNION ALL
        SELECT 'OSS_USR_PERM' FROM dual UNION ALL
        SELECT 'OSS_USR_ROL' FROM dual UNION ALL
        SELECT 'OSS_USUARIO_ROL' FROM dual
       ) req
 WHERE NOT EXISTS (
       SELECT 1
         FROM USER_TABLES obj
        WHERE obj.TABLE_NAME = req.TABLE_NAME
       );

PROMPT Modulo Soporte
SELECT CODIGO_MOD, CODIGO, NOMBRE, ACTIVO
  FROM OSS_MOD
 WHERE CODIGO = 'SOP';

PROMPT Menus Soporte esperados
SELECT CODIGO_MENU, CODIGO_MOD, CODIGO_PADRE, TITULO, PATH, ACTIVO
  FROM OSS_MENU
 WHERE CODIGO_MENU IN (1100, 1110, 1120, 1130, 1140)
 ORDER BY CODIGO_MENU;

PROMPT Permisos Soporte esperados
SELECT CODIGO_PERM, CLAVE, ACTIVO
  FROM OSS_PERM
 WHERE CLAVE LIKE 'soporte.%'
 ORDER BY CODIGO_PERM;

PROMPT Roles Soporte esperados
SELECT CODIGO_ROL, CLAVE, NOMBRE, ACTIVO
  FROM OSS_ROL
 WHERE CLAVE IN ('SOPORTE_USUARIO', 'SOPORTE_AGENTE', 'SOPORTE_ADMIN')
 ORDER BY CODIGO_ROL;

PROMPT Roles genericos de menu por modulo
SELECT CODIGO_ROL, CODIGO_MOD, CLAVE, NOMBRE, ACTIVO
  FROM OSS_ROL
 WHERE CLAVE IN (
       'SIS_MENU',
       'SOP_MENU',
       'CNT_MENU',
       'RH_MENU',
       'PRE_MENU',
       'ADM_MENU',
       'BM_MENU',
       'APP_MENU'
       )
 ORDER BY CODIGO_ROL;

PROMPT Usuarios con roles Soporte normalizados
SELECT ur.CODIGO_USUARIO,
       u.LOGIN,
       r.CLAVE,
       ur.CODIGO_EMPRESA,
       ur.ACTIVO
  FROM OSS_USR_ROL ur
  JOIN OSS_ROL r ON r.CODIGO_ROL = ur.CODIGO_ROL
  LEFT JOIN SIS_USUARIOS u ON u.CODIGO_USUARIO = ur.CODIGO_USUARIO
 WHERE r.CLAVE LIKE 'SOPORTE_%'
 ORDER BY ur.CODIGO_USUARIO, r.CLAVE;

PROMPT Usuarios con cache JSON_MENU que contiene Soporte
SELECT r.CODIGO_USUARIO_ROL,
       r.CODIGO_USUARIO,
       r.USUARIO,
       r.DESCRIPCION
  FROM OSS_USUARIO_ROL r
 WHERE DBMS_LOB.INSTR(r.JSON_MENU, '/apps/soporte/') > 0
    OR DBMS_LOB.INSTR(r.JSON_MENU, 'soporte.') > 0
 ORDER BY r.CODIGO_USUARIO;

PROMPT Validacion finalizada
