ALTER TABLE "SIS"."SIS_USUARIOS" ADD (
    "EMAIL" VARCHAR2(150), 
    "RECIBE_EMAIL" NUMBER(1,0) DEFAULT 1 NOT NULL, 
    "ES_ANALISTA_SOPORTE" NUMBER(1,0) DEFAULT 0 NOT NULL, 
    "ES_ADMIN_CNT" NUMBER(1,0) DEFAULT 0 NOT NULL, 
    "ES_ANALISTA_CNT" NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE "SIS"."OSS_USUARIO_ROL" MODIFY ("JSON_MENU" CLOB);
