CREATE OR REPLACE PROCEDURE SP_RM_CONTRI_GET_ID
(
  p_CodigoContribuyente IN NUMBER, p_CodigoEmpresa IN NUMBER,
  p_Contribuyente OUT SYS_REFCURSOR, p_Direcciones OUT SYS_REFCURSOR,
  p_Comunicaciones OUT SYS_REFCURSOR, p_Message OUT VARCHAR2
)
AS
  v_Count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_Count FROM RM_CONTRIBUYENTES
   WHERE CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
     AND CODIGO_EMPRESA = p_CodigoEmpresa;
  IF v_Count = 0 THEN p_Message := 'No se encontró el contribuyente solicitado.';
  ELSE p_Message := 'success'; END IF;

  OPEN p_Contribuyente FOR
    SELECT CODIGO_CONTRIBUYENTE, IDENTIFICACION_ID, NUMERO_IDENTIFICACION,
           NOMBRE_RAZON_SOCIAL, APELLIDO_ACRONIMO, ESTATUS_ID, FECHA_INGRESO
      FROM RM_CONTRIBUYENTES
     WHERE CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
       AND CODIGO_EMPRESA = p_CodigoEmpresa;
  OPEN p_Direcciones FOR
    SELECT CODIGO_DIRECCION, PAIS_ID, ESTADO_ID, MUNICIPIO_ID, CIUDAD_ID,
           PARROQUIA_ID, SECTOR_ID, VIALIDAD, VIVIENDA, NUMERO_UNIDAD,
           COMPLEMENTO_DIR, PRINCIPAL
      FROM RM_DIRECCIONES
     WHERE CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
       AND CODIGO_EMPRESA = p_CodigoEmpresa
     ORDER BY PRINCIPAL DESC, CODIGO_DIRECCION;
  OPEN p_Comunicaciones FOR
    SELECT CODIGO_COMUNICACION, TIPO_COMUNICACION_ID, CODIGO_AREA,
           LINEA_COMUNICACION, EXTENSION, PRINCIPAL
      FROM RM_COMUNICACIONES
     WHERE CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
       AND CODIGO_EMPRESA = p_CodigoEmpresa
     ORDER BY PRINCIPAL DESC, CODIGO_COMUNICACION;
END SP_RM_CONTRI_GET_ID;
/
