-- Sincroniza la secuencia con la PK existente. Compatible con Oracle 10g,
-- donde ALTER SEQUENCE ... RESTART no esta disponible.
DECLARE
    V_MAX_ID NUMBER;
    V_SEQ_ID NUMBER;
    V_SALTO NUMBER;
BEGIN
    SELECT NVL(MAX(CODIGO_BM_CONTEO_DETALLE), 0)
      INTO V_MAX_ID
      FROM BM.BM_CONTEO_DETALLE;

    SELECT BM.BM_S_CODIGO_CONTEO_DET.NEXTVAL
      INTO V_SEQ_ID
      FROM DUAL;

    IF V_SEQ_ID <= V_MAX_ID THEN
        V_SALTO := V_MAX_ID - V_SEQ_ID + 1;

        EXECUTE IMMEDIATE
            'ALTER SEQUENCE BM.BM_S_CODIGO_CONTEO_DET INCREMENT BY ' ||
            TO_CHAR(V_SALTO);

        SELECT BM.BM_S_CODIGO_CONTEO_DET.NEXTVAL
          INTO V_SEQ_ID
          FROM DUAL;

        EXECUTE IMMEDIATE
            'ALTER SEQUENCE BM.BM_S_CODIGO_CONTEO_DET INCREMENT BY 1';
    END IF;
END;
/

SELECT (SELECT NVL(MAX(CODIGO_BM_CONTEO_DETALLE), 0)
          FROM BM.BM_CONTEO_DETALLE) MAX_ID,
       BM.BM_S_CODIGO_CONTEO_DET.NEXTVAL NEXT_ID
  FROM DUAL;
