DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO v_count
    FROM all_tab_cols
   WHERE owner = 'SIS'
     AND table_name = 'SIS_USUARIOS'
     AND column_name = 'ES_ANALISTA_SOPORTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SIS.SIS_USUARIOS ADD ES_ANALISTA_SOPORTE NUMBER(1) DEFAULT 0 NOT NULL';
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE SIS.SP_SIS_USR_GET_ALL (
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_SearchText IN VARCHAR2,
  p_SOLO_ACTIVOS IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2,
  p_TotalRecords OUT NUMBER,
  p_TotalPages OUT NUMBER
) AS
  v_from NUMBER;
  v_to NUMBER;
BEGIN
  v_from := ((NVL(p_PageNumber, 1) - 1) * NVL(p_PageSize, 10)) + 1;
  v_to := NVL(p_PageNumber, 1) * NVL(p_PageSize, 10);

  SELECT COUNT(1) INTO p_TotalRecords
    FROM SIS.SIS_USUARIOS u
   WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND (NVL(p_SOLO_ACTIVOS, 0) = 0 OR NVL(u.STATUS, 'A') IN ('1', 'A'))
     AND (p_SearchText IS NULL OR UPPER(u.USUARIO || ' ' || u.LOGIN || ' ' || TO_CHAR(u.CEDULA) || ' ' || NVL(u.EMAIL, '')) LIKE '%' || UPPER(p_SearchText) || '%');

  p_TotalPages := CEIL(p_TotalRecords / NVL(p_PageSize, 10));

  OPEN p_ResultSet FOR
    SELECT CODIGO_USUARIO, USUARIO, LOGIN, CEDULA, NVL(STATUS, 'A') STATUS,
           NVL(EMAIL, '') EMAIL, NVL(RECIBE_EMAIL, 1) RECIBE_EMAIL,
           NVL(ES_ANALISTA_SOPORTE, 0) ES_ANALISTA_SOPORTE,
           NVL(IS_SUPERUSER, 0) IS_SUPERUSER, CODIGO_EMPRESA
      FROM (
        SELECT q.*, ROWNUM rn
          FROM (
            SELECT *
              FROM SIS.SIS_USUARIOS u
             WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
               AND (NVL(p_SOLO_ACTIVOS, 0) = 0 OR NVL(u.STATUS, 'A') IN ('1', 'A'))
               AND (p_SearchText IS NULL OR UPPER(u.USUARIO || ' ' || u.LOGIN || ' ' || TO_CHAR(u.CEDULA) || ' ' || NVL(u.EMAIL, '')) LIKE '%' || UPPER(p_SearchText) || '%')
             ORDER BY u.USUARIO
          ) q
         WHERE ROWNUM <= v_to
      )
     WHERE rn >= v_from;

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_TotalRecords := 0;
    p_TotalPages := 0;
    p_Message := SQLERRM;
    OPEN p_ResultSet FOR
      SELECT CAST(NULL AS NUMBER) CODIGO_USUARIO,
             CAST(NULL AS VARCHAR2(200)) USUARIO,
             CAST(NULL AS VARCHAR2(100)) LOGIN,
             CAST(NULL AS NUMBER) CEDULA,
             CAST(NULL AS VARCHAR2(10)) STATUS,
             CAST(NULL AS VARCHAR2(150)) EMAIL,
             CAST(NULL AS NUMBER) RECIBE_EMAIL,
             CAST(NULL AS NUMBER) ES_ANALISTA_SOPORTE,
             CAST(NULL AS NUMBER) IS_SUPERUSER,
             CAST(NULL AS NUMBER) CODIGO_EMPRESA
        FROM DUAL
       WHERE 1 = 0;
END;
/

CREATE OR REPLACE PROCEDURE SIS.SP_SIS_USR_GET_ID (
  p_CODIGO_USUARIO IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT CODIGO_USUARIO, USUARIO, LOGIN, CEDULA, NVL(STATUS, 'A') STATUS,
           NVL(EMAIL, '') EMAIL, NVL(RECIBE_EMAIL, 1) RECIBE_EMAIL,
           NVL(ES_ANALISTA_SOPORTE, 0) ES_ANALISTA_SOPORTE,
           NVL(IS_SUPERUSER, 0) IS_SUPERUSER, CODIGO_EMPRESA
      FROM SIS.SIS_USUARIOS
     WHERE CODIGO_USUARIO = p_CODIGO_USUARIO
       AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SIS.SP_SIS_USR_EMAIL_UPD (
  p_CODIGO_USUARIO IN NUMBER,
  p_EMAIL IN VARCHAR2,
  p_RECIBE_EMAIL IN NUMBER,
  p_ES_ANALISTA_SOPORTE IN NUMBER,
  p_IS_SUPERUSER IN NUMBER,
  p_USUARIO_UPD IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SIS.SIS_USUARIOS
     SET EMAIL = p_EMAIL,
         RECIBE_EMAIL = NVL(p_RECIBE_EMAIL, 1),
         ES_ANALISTA_SOPORTE = NVL(p_ES_ANALISTA_SOPORTE, 0),
         IS_SUPERUSER = NVL(p_IS_SUPERUSER, 0),
         USUARIO_UPD = p_USUARIO_UPD,
         FECHA_UPD = SYSDATE
   WHERE CODIGO_USUARIO = p_CODIGO_USUARIO
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  IF SQL%ROWCOUNT = 0 THEN
    p_Message := 'No se encontro el usuario indicado.';
  ELSE
    p_Message := 'Success';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SIS.SP_SIS_USR_GET_SUPP (
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_SearchText IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT *
      FROM (
        SELECT CODIGO_USUARIO, USUARIO, LOGIN, CEDULA, NVL(STATUS, 'A') STATUS,
               NVL(EMAIL, '') EMAIL, NVL(RECIBE_EMAIL, 1) RECIBE_EMAIL,
               NVL(ES_ANALISTA_SOPORTE, 0) ES_ANALISTA_SOPORTE,
               NVL(IS_SUPERUSER, 0) IS_SUPERUSER, CODIGO_EMPRESA
          FROM SIS.SIS_USUARIOS
         WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
           AND NVL(STATUS, 'A') IN ('1', 'A')
           AND NVL(ES_ANALISTA_SOPORTE, 0) = 1
           AND (p_SearchText IS NULL OR UPPER(USUARIO || ' ' || LOGIN || ' ' || NVL(EMAIL, '')) LIKE '%' || UPPER(p_SearchText) || '%')
         ORDER BY USUARIO
      )
     WHERE ROWNUM <= NVL(p_PageSize, 25);
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
    OPEN p_ResultSet FOR
      SELECT CAST(NULL AS NUMBER) CODIGO_USUARIO,
             CAST(NULL AS VARCHAR2(200)) USUARIO,
             CAST(NULL AS VARCHAR2(100)) LOGIN,
             CAST(NULL AS NUMBER) CEDULA,
             CAST(NULL AS VARCHAR2(10)) STATUS,
             CAST(NULL AS VARCHAR2(150)) EMAIL,
             CAST(NULL AS NUMBER) RECIBE_EMAIL,
             CAST(NULL AS NUMBER) ES_ANALISTA_SOPORTE,
             CAST(NULL AS NUMBER) IS_SUPERUSER,
             CAST(NULL AS NUMBER) CODIGO_EMPRESA
        FROM DUAL
       WHERE 1 = 0;
END;
/

SHOW ERRORS PROCEDURE SIS.SP_SIS_USR_GET_ALL;
SHOW ERRORS PROCEDURE SIS.SP_SIS_USR_GET_ID;
SHOW ERRORS PROCEDURE SIS.SP_SIS_USR_EMAIL_UPD;
SHOW ERRORS PROCEDURE SIS.SP_SIS_USR_GET_SUPP;

SELECT owner, object_name, object_type, status
  FROM all_objects
 WHERE owner = 'SIS'
   AND object_name IN (
     'SP_SIS_USR_GET_ALL',
     'SP_SIS_USR_GET_ID',
     'SP_SIS_USR_EMAIL_UPD',
     'SP_SIS_USR_GET_SUPP'
   )
 ORDER BY object_name;
