DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_tab_cols WHERE table_name = 'SIS_USUARIOS' AND column_name = 'EMAIL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SIS_USUARIOS ADD EMAIL VARCHAR2(150)';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tab_cols WHERE table_name = 'SIS_USUARIOS' AND column_name = 'RECIBE_EMAIL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SIS_USUARIOS ADD RECIBE_EMAIL NUMBER(1) DEFAULT 1 NOT NULL';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tab_cols WHERE table_name = 'SIS_USUARIOS' AND column_name = 'ES_ANALISTA_SOPORTE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SIS_USUARIOS ADD ES_ANALISTA_SOPORTE NUMBER(1) DEFAULT 0 NOT NULL';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tab_cols WHERE table_name = 'SIS_USUARIOS' AND column_name = 'ES_ANALISTA_CNT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SIS_USUARIOS ADD ES_ANALISTA_CNT NUMBER(1) DEFAULT 0 NOT NULL';
  END IF;

  SELECT COUNT(1) INTO v_count FROM user_tab_cols WHERE table_name = 'SIS_USUARIOS' AND column_name = 'ES_ADMIN_CNT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SIS_USUARIOS ADD ES_ADMIN_CNT NUMBER(1) DEFAULT 0 NOT NULL';
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_GET_ALL (
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_SearchText IN VARCHAR2,
  p_SOLO_ACTIVOS IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2,
  p_TotalRecords OUT NUMBER,
  p_TotalPages OUT NUMBER
) AS
  v_from NUMBER;
  v_to NUMBER;
BEGIN
  v_from := ((NVL(p_PageNumber, 1) - 1) * NVL(p_PageSize, 10)) + 1;
  v_to := NVL(p_PageNumber, 1) * NVL(p_PageSize, 10);

  SELECT COUNT(1) INTO p_TotalRecords
    FROM SIS_USUARIOS u
   WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND (NVL(p_SOLO_ACTIVOS, 0) = 0 OR NVL(u.STATUS, 'A') = 'A')
     AND (p_SearchText IS NULL OR UPPER(u.USUARIO || ' ' || u.LOGIN || ' ' || TO_CHAR(u.CEDULA)) LIKE '%' || UPPER(p_SearchText) || '%');

  p_TotalPages := CEIL(p_TotalRecords / NVL(p_PageSize, 10));

  OPEN p_ResultSet FOR
    SELECT CODIGO_USUARIO, USUARIO, LOGIN, CEDULA, NVL(STATUS, 'A') STATUS,
           NVL(EMAIL, '') EMAIL, NVL(RECIBE_EMAIL, 1) RECIBE_EMAIL,
           NVL(ES_ANALISTA_SOPORTE, 0) ES_ANALISTA_SOPORTE,
           NVL(ES_ANALISTA_CNT, 0) ES_ANALISTA_CNT,
           NVL(ES_ADMIN_CNT, 0) ES_ADMIN_CNT,
           NVL(IS_SUPERUSER, 0) IS_SUPERUSER, CODIGO_EMPRESA
      FROM (
        SELECT q.*, ROWNUM rn
          FROM (
            SELECT *
              FROM SIS_USUARIOS u
             WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
               AND (NVL(p_SOLO_ACTIVOS, 0) = 0 OR NVL(u.STATUS, 'A') = 'A')
               AND (p_SearchText IS NULL OR UPPER(u.USUARIO || ' ' || u.LOGIN || ' ' || TO_CHAR(u.CEDULA)) LIKE '%' || UPPER(p_SearchText) || '%')
             ORDER BY u.USUARIO
          ) q
         WHERE ROWNUM <= v_to
      )
     WHERE rn >= v_from;

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_GET_ID (
  p_CODIGO_USUARIO IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT CODIGO_USUARIO, USUARIO, LOGIN, CEDULA, NVL(STATUS, 'A') STATUS,
           NVL(EMAIL, '') EMAIL, NVL(RECIBE_EMAIL, 1) RECIBE_EMAIL,
           NVL(ES_ANALISTA_SOPORTE, 0) ES_ANALISTA_SOPORTE,
           NVL(ES_ANALISTA_CNT, 0) ES_ANALISTA_CNT,
           NVL(ES_ADMIN_CNT, 0) ES_ADMIN_CNT,
           NVL(IS_SUPERUSER, 0) IS_SUPERUSER, CODIGO_EMPRESA
      FROM SIS_USUARIOS
     WHERE CODIGO_USUARIO = p_CODIGO_USUARIO
       AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_INS (
  p_USUARIO IN VARCHAR2,
  p_LOGIN IN VARCHAR2,
  p_CLAVE IN VARCHAR2,
  p_CEDULA IN NUMBER,
  p_EMAIL IN VARCHAR2,
  p_RECIBE_EMAIL IN NUMBER,
  p_ES_ANALISTA_SOPORTE IN NUMBER,
  p_ES_ANALISTA_CNT IN NUMBER,
  p_ES_ADMIN_CNT IN NUMBER,
  p_IS_SUPERUSER IN NUMBER,
  p_USUARIO_INS IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_CODIGO_USUARIO_OUT OUT NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  SELECT NVL(MAX(CODIGO_USUARIO), 0) + 1 INTO p_CODIGO_USUARIO_OUT FROM SIS_USUARIOS;

  INSERT INTO SIS_USUARIOS (
    CODIGO_USUARIO, USUARIO, LOGIN, PASSWORD, CEDULA, STATUS,
    EMAIL, RECIBE_EMAIL, ES_ANALISTA_SOPORTE, ES_ANALISTA_CNT, ES_ADMIN_CNT, IS_SUPERUSER, USUARIO_INS, FECHA_INS, CODIGO_EMPRESA
  ) VALUES (
    p_CODIGO_USUARIO_OUT, p_USUARIO, p_LOGIN, SIS_ENCRYPTED(p_CLAVE), p_CEDULA, 'A',
    p_EMAIL, NVL(p_RECIBE_EMAIL, 1), NVL(p_ES_ANALISTA_SOPORTE, 0), NVL(p_ES_ANALISTA_CNT, 0), NVL(p_ES_ADMIN_CNT, 0), NVL(p_IS_SUPERUSER, 0), p_USUARIO_INS, SYSDATE, p_CODIGO_EMPRESA
  );

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_CODIGO_USUARIO_OUT := 0;
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_UPD (
  p_CODIGO_USUARIO IN NUMBER,
  p_USUARIO IN VARCHAR2,
  p_LOGIN IN VARCHAR2,
  p_CEDULA IN NUMBER,
  p_STATUS IN VARCHAR2,
  p_EMAIL IN VARCHAR2,
  p_RECIBE_EMAIL IN NUMBER,
  p_ES_ANALISTA_SOPORTE IN NUMBER,
  p_ES_ANALISTA_CNT IN NUMBER,
  p_ES_ADMIN_CNT IN NUMBER,
  p_IS_SUPERUSER IN NUMBER,
  p_USUARIO_UPD IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SIS_USUARIOS
     SET USUARIO = p_USUARIO,
         LOGIN = p_LOGIN,
         CEDULA = p_CEDULA,
         STATUS = p_STATUS,
         EMAIL = p_EMAIL,
         RECIBE_EMAIL = NVL(p_RECIBE_EMAIL, 1),
         ES_ANALISTA_SOPORTE = NVL(p_ES_ANALISTA_SOPORTE, 0),
         ES_ANALISTA_CNT = NVL(p_ES_ANALISTA_CNT, 0),
         ES_ADMIN_CNT = NVL(p_ES_ADMIN_CNT, 0),
         IS_SUPERUSER = NVL(p_IS_SUPERUSER, 0),
         USUARIO_UPD = p_USUARIO_UPD,
         FECHA_UPD = SYSDATE
   WHERE CODIGO_USUARIO = p_CODIGO_USUARIO
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  IF SQL%ROWCOUNT = 0 THEN
    p_Message := 'No se encontró el usuario indicado.';
  ELSE
    p_Message := 'Success';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_EMAIL_UPD (
  p_CODIGO_USUARIO IN NUMBER,
  p_EMAIL IN VARCHAR2,
  p_RECIBE_EMAIL IN NUMBER,
  p_ES_ANALISTA_SOPORTE IN NUMBER,
  p_ES_ANALISTA_CNT IN NUMBER,
  p_ES_ADMIN_CNT IN NUMBER,
  p_IS_SUPERUSER IN NUMBER,
  p_USUARIO_UPD IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SIS_USUARIOS
     SET EMAIL = p_EMAIL,
         RECIBE_EMAIL = NVL(p_RECIBE_EMAIL, 1),
         ES_ANALISTA_SOPORTE = NVL(p_ES_ANALISTA_SOPORTE, 0),
         ES_ANALISTA_CNT = NVL(p_ES_ANALISTA_CNT, 0),
         ES_ADMIN_CNT = NVL(p_ES_ADMIN_CNT, 0),
         IS_SUPERUSER = NVL(p_IS_SUPERUSER, 0),
         USUARIO_UPD = p_USUARIO_UPD,
         FECHA_UPD = SYSDATE
   WHERE CODIGO_USUARIO = p_CODIGO_USUARIO
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  IF SQL%ROWCOUNT = 0 THEN
    p_Message := 'No se encontró el usuario indicado.';
  ELSE
    p_Message := 'Success';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_PASS_UPD (
  p_CODIGO_USUARIO IN NUMBER,
  p_CLAVE IN VARCHAR2,
  p_USUARIO_UPD IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SIS_USUARIOS
     SET PASSWORD = SIS_ENCRYPTED(p_CLAVE),
         USUARIO_UPD = p_USUARIO_UPD,
         FECHA_UPD = SYSDATE
   WHERE CODIGO_USUARIO = p_CODIGO_USUARIO
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  IF SQL%ROWCOUNT = 0 THEN
    p_Message := 'No se encontró el usuario indicado.';
  ELSE
    p_Message := 'Success';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SIS_USR_GET_SUPP (
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_SearchText IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT *
      FROM (
        SELECT CODIGO_USUARIO, USUARIO, LOGIN, CEDULA, NVL(STATUS, 'A') STATUS,
               NVL(EMAIL, '') EMAIL, NVL(RECIBE_EMAIL, 1) RECIBE_EMAIL,
               NVL(ES_ANALISTA_SOPORTE, 0) ES_ANALISTA_SOPORTE,
               NVL(ES_ANALISTA_CNT, 0) ES_ANALISTA_CNT,
               NVL(ES_ADMIN_CNT, 0) ES_ADMIN_CNT,
               NVL(IS_SUPERUSER, 0) IS_SUPERUSER, CODIGO_EMPRESA
          FROM SIS_USUARIOS
         WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
           AND NVL(STATUS, 'A') IN ('1', 'A')
           AND NVL(ES_ANALISTA_SOPORTE, 0) = 1
           AND (p_SearchText IS NULL OR UPPER(USUARIO || ' ' || LOGIN || ' ' || NVL(EMAIL, '')) LIKE '%' || UPPER(p_SearchText) || '%')
         ORDER BY USUARIO
      )
     WHERE ROWNUM <= NVL(p_PageSize, 25);
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/
