CREATE TABLE SIS_EMAIL_CONFIG (
  CONFIG_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  SMTP_HOST VARCHAR2(200) NOT NULL,
  SMTP_PORT NUMBER(10) NOT NULL,
  SMTP_USER VARCHAR2(200),
  SMTP_PASS VARCHAR2(400),
  SMTP_SSL NUMBER(1) DEFAULT 1 NOT NULL,
  FROM_EMAIL VARCHAR2(150) NOT NULL,
  FROM_NAME VARCHAR2(150),
  ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE
);

CREATE TABLE SIS_EMAIL_QUEUE (
  EMAIL_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  MODULO_ORIGEN VARCHAR2(40) NOT NULL,
  REFERENCIA_ID NUMBER(10),
  TO_EMAIL VARCHAR2(150) NOT NULL,
  TO_NAME VARCHAR2(150),
  SUBJECT VARCHAR2(250) NOT NULL,
  BODY_HTML CLOB,
  BODY_TEXT CLOB,
  ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  INTENTOS NUMBER(5) DEFAULT 0 NOT NULL,
  MAX_INTENTOS NUMBER(5) DEFAULT 3 NOT NULL,
  FECHA_PROGRAMADA DATE DEFAULT SYSDATE,
  FECHA_ENVIO DATE,
  MESSAGE_ID VARCHAR2(200),
  ERROR_ENVIO VARCHAR2(1000),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE
);

CREATE SEQUENCE SEQ_EMAIL_CFG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMAIL_Q START WITH 1 INCREMENT BY 1;

ALTER TABLE SIS_EMAIL_CONFIG ADD CONSTRAINT PK_EMAIL_CFG PRIMARY KEY (CONFIG_ID);
ALTER TABLE SIS_EMAIL_QUEUE ADD CONSTRAINT PK_EMAIL_Q PRIMARY KEY (EMAIL_ID);

CREATE INDEX IX_EMAIL_Q_STATUS ON SIS_EMAIL_QUEUE(CODIGO_EMPRESA, ESTADO, FECHA_PROGRAMADA);
