CREATE OR REPLACE PROCEDURE SP_EMAIL_Q_INS (
  p_MODULO_ORIGEN IN VARCHAR2,
  p_REFERENCIA_ID IN NUMBER,
  p_TO_EMAIL IN VARCHAR2,
  p_TO_NAME IN VARCHAR2,
  p_SUBJECT IN VARCHAR2,
  p_BODY_HTML IN CLOB,
  p_BODY_TEXT IN CLOB,
  p_FECHA_PROGRAMADA IN DATE,
  p_CODIGO_EMPRESA IN NUMBER,
  p_EMAIL_ID_OUT OUT NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  p_EMAIL_ID_OUT := SEQ_EMAIL_Q.NEXTVAL;
  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  ) VALUES (
    p_EMAIL_ID_OUT, p_CODIGO_EMPRESA, p_MODULO_ORIGEN, p_REFERENCIA_ID,
    p_TO_EMAIL, p_TO_NAME, p_SUBJECT, p_BODY_HTML, p_BODY_TEXT,
    NVL(p_FECHA_PROGRAMADA, SYSDATE)
  );
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_EMAIL_ID_OUT := 0;
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_EMAIL_Q_GET_PEND (
  p_PageSize IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT EMAIL_ID, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL, NVL(TO_NAME, '') TO_NAME,
           SUBJECT, NVL(BODY_HTML, '') BODY_HTML, NVL(BODY_TEXT, '') BODY_TEXT,
           ESTADO, INTENTOS, MAX_INTENTOS, FECHA_PROGRAMADA, FECHA_ENVIO,
           NVL(ERROR_ENVIO, '') ERROR_ENVIO
      FROM SIS_EMAIL_QUEUE
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND ESTADO IN ('PENDIENTE', 'ERROR')
       AND INTENTOS < MAX_INTENTOS
       AND NVL(FECHA_PROGRAMADA, SYSDATE) <= SYSDATE
       AND ROWNUM <= NVL(p_PageSize, 25)
     ORDER BY FECHA_PROGRAMADA, EMAIL_ID;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_EMAIL_Q_SENT (
  p_EMAIL_ID IN NUMBER,
  p_MESSAGE_ID IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SIS_EMAIL_QUEUE
     SET ESTADO = 'ENVIADO',
         FECHA_ENVIO = SYSDATE,
         MESSAGE_ID = p_MESSAGE_ID,
         UPDATED_AT = SYSDATE
   WHERE EMAIL_ID = p_EMAIL_ID
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_EMAIL_Q_ERROR (
  p_EMAIL_ID IN NUMBER,
  p_ERROR_ENVIO IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SIS_EMAIL_QUEUE
     SET ESTADO = 'ERROR',
         INTENTOS = INTENTOS + 1,
         ERROR_ENVIO = p_ERROR_ENVIO,
         UPDATED_AT = SYSDATE
   WHERE EMAIL_ID = p_EMAIL_ID
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_EMAIL_CFG_GET (
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT CONFIG_ID, CODIGO_EMPRESA, SMTP_HOST, SMTP_PORT, SMTP_USER,
           SMTP_PASS, SMTP_SSL, FROM_EMAIL, FROM_NAME, ACTIVO
      FROM SIS_EMAIL_CONFIG
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND ACTIVO = 1
       AND ROWNUM = 1;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/
