CREATE OR REPLACE PROCEDURE SP_CAT_PAR_GET_ALL
(p_Ano IN NUMBER, p_CodigoEmpresa IN NUMBER, p_Ajustes OUT SYS_REFCURSOR,
 p_Tabla OUT SYS_REFCURSOR, p_Zonas OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN p_Ajustes FOR SELECT PORCENTAJE, ALICUOTA, NOMBRE_DIRECTOR,
    DIAS_MULTA_CAMBIO_FIRMA, UNIDAD_TRIBUTARIA, NUMERO_RESOLUCION,
    FECHA_RESOLUCION, DENOMINACION, BASE_JURIDICA FROM CAT_AJUSTES;
  OPEN p_Tabla FOR SELECT ANO, ESTADO, MUNICIPIO, PARROQUIA, AMBITO,
    TIPO, TIPO_UNIDAD, VALOR, DESCRIPCION, PORCENTAJE, VALOR_AJUSTADO,
    TIPO_CALCULO, DEPRECIA, AJUSTE FROM CAT_TABLA_IMP
    WHERE (p_Ano IS NULL OR ANO = p_Ano)
    ORDER BY ANO DESC, ESTADO, MUNICIPIO, PARROQUIA, AMBITO, TIPO, TIPO_UNIDAD;
  OPEN p_Zonas FOR SELECT CODIGO_ZONIFICACION, CODIGO, DESCRIPCION
    FROM CAT_ZONIFICACIONES WHERE CODIGO_EMPRESA = p_CodigoEmpresa
    ORDER BY CODIGO, DESCRIPCION;
END SP_CAT_PAR_GET_ALL;
/
