PROMPT Compilando stored procedures de SIS OSS Usuario Rol...

@@SP_OSS_USR_ROL_INS.sql
@@SP_OSS_USR_ROL_UPD.sql
@@SP_OSS_USR_ROL_DEL.sql
@@SP_OSS_USR_ROL_GET_ID.sql
@@SP_OSS_USR_ROL_GET_ALL.sql
@@SP_OSS_USR_ROL_GET_USR.sql

PROMPT Validando estado de stored procedures de SIS OSS Usuario Rol...

SELECT object_name, status
  FROM user_objects
 WHERE object_type = 'PROCEDURE'
   AND object_name IN (
       'SP_OSS_USR_ROL_INS',
       'SP_OSS_USR_ROL_UPD',
       'SP_OSS_USR_ROL_DEL',
       'SP_OSS_USR_ROL_GET_ID',
       'SP_OSS_USR_ROL_GET_ALL',
       'SP_OSS_USR_ROL_GET_USR'
   )
 ORDER BY object_name;

SHOW ERRORS PROCEDURE SP_OSS_USR_ROL_INS
SHOW ERRORS PROCEDURE SP_OSS_USR_ROL_UPD
SHOW ERRORS PROCEDURE SP_OSS_USR_ROL_DEL
SHOW ERRORS PROCEDURE SP_OSS_USR_ROL_GET_ID
SHOW ERRORS PROCEDURE SP_OSS_USR_ROL_GET_ALL
SHOW ERRORS PROCEDURE SP_OSS_USR_ROL_GET_USR
