PROMPT Migracion de SIS.OSS_USUARIO_ROL.JSON_MENU de LONG a CLOB.
PROMPT Ejecutar en una ventana controlada y con respaldo previo.

CREATE TABLE SIS.OSS_USUARIO_ROL_BKP AS
SELECT CODIGO_USUARIO_ROL,
       USUARIO,
       CODIGO_USUARIO,
       DESCRIPCION,
       TO_LOB(JSON_MENU) JSON_MENU
  FROM SIS.OSS_USUARIO_ROL;

CREATE TABLE SIS.OSS_USUARIO_ROL_NEW (
    CODIGO_USUARIO_ROL NUMBER,
    USUARIO            VARCHAR2(50),
    CODIGO_USUARIO     NUMBER,
    DESCRIPCION        VARCHAR2(100),
    JSON_MENU          CLOB
) TABLESPACE SAMI_DATA01;

INSERT INTO SIS.OSS_USUARIO_ROL_NEW (
    CODIGO_USUARIO_ROL,
    USUARIO,
    CODIGO_USUARIO,
    DESCRIPCION,
    JSON_MENU
)
SELECT CODIGO_USUARIO_ROL,
       USUARIO,
       CODIGO_USUARIO,
       DESCRIPCION,
       TO_LOB(JSON_MENU)
  FROM SIS.OSS_USUARIO_ROL;

COMMIT;

PROMPT Validar registros antes de renombrar:
SELECT COUNT(*) REGISTROS_ORIGEN FROM SIS.OSS_USUARIO_ROL;
SELECT COUNT(*) REGISTROS_NUEVA FROM SIS.OSS_USUARIO_ROL_NEW;

PROMPT Si el conteo es correcto, ejecutar manualmente:
PROMPT ALTER TABLE SIS.OSS_USUARIO_ROL RENAME TO OSS_USUARIO_ROL_LONG;
PROMPT ALTER TABLE SIS.OSS_USUARIO_ROL_NEW RENAME TO OSS_USUARIO_ROL;
