CREATE OR REPLACE PROCEDURE SIS.SP_OSS_USR_ROL_GET_USR (
    p_USUARIO    IN VARCHAR2,
    p_ResultSet  OUT SYS_REFCURSOR,
    p_Message    OUT VARCHAR2
) AS
BEGIN
    OPEN p_ResultSet FOR
        SELECT CODIGO_USUARIO_ROL,
               USUARIO,
               CODIGO_USUARIO,
               DESCRIPCION,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 1) JSON_MENU_01,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 4001) JSON_MENU_02,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 8001) JSON_MENU_03,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 12001) JSON_MENU_04,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 16001) JSON_MENU_05,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 20001) JSON_MENU_06,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 24001) JSON_MENU_07,
               DBMS_LOB.SUBSTR(JSON_MENU, 4000, 28001) JSON_MENU_08
          FROM SIS.OSS_USUARIO_ROL
         WHERE UPPER(TRIM(USUARIO)) = UPPER(TRIM(p_USUARIO))
         ORDER BY CODIGO_USUARIO_ROL DESC;

    p_Message := 'suscces';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
        OPEN p_ResultSet FOR
            SELECT CAST(NULL AS NUMBER) CODIGO_USUARIO_ROL,
                   CAST(NULL AS VARCHAR2(50)) USUARIO,
                   CAST(NULL AS NUMBER) CODIGO_USUARIO,
                   CAST(NULL AS VARCHAR2(100)) DESCRIPCION,
                   EMPTY_CLOB() JSON_MENU
              FROM DUAL
             WHERE 1 = 0;
END SP_OSS_USR_ROL_GET_USR;
/
