CREATE OR REPLACE PROCEDURE SIS.SP_OSS_USR_ROL_DEL (
    p_CODIGO_USUARIO_ROL IN NUMBER,
    p_Message            OUT VARCHAR2
) AS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO v_exists
      FROM SIS.OSS_USUARIO_ROL
     WHERE CODIGO_USUARIO_ROL = p_CODIGO_USUARIO_ROL;

    IF v_exists = 0 THEN
        p_Message := 'CODIGO_USUARIO_ROL no existe en SIS.OSS_USUARIO_ROL';
        RETURN;
    END IF;

    DELETE FROM SIS.OSS_USUARIO_ROL
     WHERE CODIGO_USUARIO_ROL = p_CODIGO_USUARIO_ROL;

    p_Message := 'suscces';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
END SP_OSS_USR_ROL_DEL;
/
