PROMPT Creando tablas de soporte...

CREATE TABLE SOP_TIPO_SOLICITUD (
  TIPO_SOLICITUD_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  ORDEN NUMBER(5) DEFAULT 0 NOT NULL,
  ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE
);

CREATE TABLE SOP_PRIORIDAD (
  PRIORIDAD_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  ORDEN NUMBER(5) DEFAULT 0 NOT NULL,
  HORAS_SLA NUMBER(10),
  ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE
);

CREATE TABLE SOP_ESTADO (
  ESTADO_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  ORDEN NUMBER(5) DEFAULT 0 NOT NULL,
  ES_FINAL NUMBER(1) DEFAULT 0 NOT NULL,
  ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE
);

CREATE TABLE SOP_MODULO (
  MODULO_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  ORDEN NUMBER(5) DEFAULT 0 NOT NULL,
  ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE
);

CREATE TABLE SOP_TICKET (
  TICKET_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  TICKET_NUMERO VARCHAR2(30) NOT NULL,
  USUARIO_SOLICITANTE_ID NUMBER(10) NOT NULL,
  TIPO_SOLICITUD_ID NUMBER(10) NOT NULL,
  MODULO_ID NUMBER(10) NOT NULL,
  ASUNTO VARCHAR2(200) NOT NULL,
  DESCRIPCION VARCHAR2(4000) NOT NULL,
  PRIORIDAD_ID NUMBER(10) NOT NULL,
  ESTADO_ID NUMBER(10) NOT NULL,
  USUARIO_RESPONSABLE_ID NUMBER(10),
  FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  FECHA_ASIGNACION DATE,
  FECHA_PRIMERA_RESPUESTA DATE,
  FECHA_RESOLUCION DATE,
  FECHA_CIERRE DATE,
  OBSERVACION_RESOLUCION VARCHAR2(1000),
  FECHA_VENCIMIENTO_SLA DATE,
  CREATED_BY NUMBER(10) NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_BY NUMBER(10),
  UPDATED_AT DATE
);

CREATE TABLE SOP_TICKET_COMENTARIO (
  COMENTARIO_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  TICKET_ID NUMBER(10) NOT NULL,
  USUARIO_ID NUMBER(10) NOT NULL,
  COMENTARIO VARCHAR2(4000) NOT NULL,
  ES_INTERNO NUMBER(1) DEFAULT 0 NOT NULL,
  FECHA_COMENTARIO DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SOP_TICKET_HISTORIAL (
  HISTORIAL_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  TICKET_ID NUMBER(10) NOT NULL,
  TIPO_CAMBIO VARCHAR2(30) NOT NULL,
  CAMPO VARCHAR2(60),
  VALOR_ANTERIOR VARCHAR2(500),
  VALOR_NUEVO VARCHAR2(500),
  COMENTARIO VARCHAR2(1000),
  USUARIO_ID NUMBER(10) NOT NULL,
  FECHA_CAMBIO DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SOP_TICKET_ADJUNTO (
  ADJUNTO_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  TICKET_ID NUMBER(10) NOT NULL,
  NOMBRE_ORIGINAL VARCHAR2(255) NOT NULL,
  IDENTIFICADOR_ARCHIVO VARCHAR2(255),
  RUTA_ARCHIVO VARCHAR2(500),
  MIME_TYPE VARCHAR2(120),
  TAMANO_BYTES NUMBER(18),
  USUARIO_CARGA_ID NUMBER(10) NOT NULL,
  FECHA_CARGA DATE DEFAULT SYSDATE NOT NULL,
  ACTIVO NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE SOP_TICKET_NOTIF (
  NOTIF_ID NUMBER(10) NOT NULL,
  CODIGO_EMPRESA NUMBER(10) NOT NULL,
  TICKET_ID NUMBER(10) NOT NULL,
  USUARIO_DESTINO_ID NUMBER(10) NOT NULL,
  TIPO_DESTINO VARCHAR2(20) NOT NULL,
  EVENTO VARCHAR2(30) NOT NULL,
  TITULO VARCHAR2(200) NOT NULL,
  MENSAJE VARCHAR2(1000) NOT NULL,
  CANAL VARCHAR2(20) DEFAULT 'INTERNA' NOT NULL,
  EMAIL_DESTINO VARCHAR2(150),
  LEIDA NUMBER(1) DEFAULT 0 NOT NULL,
  FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  FECHA_LECTURA DATE,
  FECHA_ENVIO DATE,
  MESSAGE_ID VARCHAR2(200),
  ERROR_ENVIO VARCHAR2(1000)
);

CREATE SEQUENCE SEQ_SOP_TIPO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_PRIOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_EST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_MOD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_TKT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_COMM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_HIST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_ATT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOP_NOTIF START WITH 1 INCREMENT BY 1;

ALTER TABLE SOP_TIPO_SOLICITUD ADD CONSTRAINT PK_SOP_TIPO PRIMARY KEY (TIPO_SOLICITUD_ID);
ALTER TABLE SOP_PRIORIDAD ADD CONSTRAINT PK_SOP_PRIOR PRIMARY KEY (PRIORIDAD_ID);
ALTER TABLE SOP_ESTADO ADD CONSTRAINT PK_SOP_EST PRIMARY KEY (ESTADO_ID);
ALTER TABLE SOP_MODULO ADD CONSTRAINT PK_SOP_MOD PRIMARY KEY (MODULO_ID);
ALTER TABLE SOP_TICKET ADD CONSTRAINT PK_SOP_TKT PRIMARY KEY (TICKET_ID);
ALTER TABLE SOP_TICKET_COMENTARIO ADD CONSTRAINT PK_SOP_COMM PRIMARY KEY (COMENTARIO_ID);
ALTER TABLE SOP_TICKET_HISTORIAL ADD CONSTRAINT PK_SOP_HIST PRIMARY KEY (HISTORIAL_ID);
ALTER TABLE SOP_TICKET_ADJUNTO ADD CONSTRAINT PK_SOP_ATT PRIMARY KEY (ADJUNTO_ID);
ALTER TABLE SOP_TICKET_NOTIF ADD CONSTRAINT PK_SOP_NOTIF PRIMARY KEY (NOTIF_ID);

CREATE INDEX IX_SOP_TKT_EMP_EST ON SOP_TICKET(CODIGO_EMPRESA, ESTADO_ID);
CREATE INDEX IX_SOP_TKT_EMP_RESP ON SOP_TICKET(CODIGO_EMPRESA, USUARIO_RESPONSABLE_ID);
CREATE INDEX IX_SOP_TKT_EMP_SOL ON SOP_TICKET(CODIGO_EMPRESA, USUARIO_SOLICITANTE_ID);
CREATE INDEX IX_SOP_NOTIF_USR ON SOP_TICKET_NOTIF(CODIGO_EMPRESA, USUARIO_DESTINO_ID, LEIDA);
