PROMPT Insertando catalogos iniciales de soporte para empresa 1...

INSERT INTO SOP_TIPO_SOLICITUD (TIPO_SOLICITUD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_TIPO.NEXTVAL, 1, 'Consulta', 'Consulta funcional o tecnica', 1);
INSERT INTO SOP_TIPO_SOLICITUD (TIPO_SOLICITUD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_TIPO.NEXTVAL, 1, 'Reporte de error', 'Incidente o error del sistema', 2);
INSERT INTO SOP_TIPO_SOLICITUD (TIPO_SOLICITUD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_TIPO.NEXTVAL, 1, 'Nuevo requerimiento', 'Nueva funcionalidad solicitada', 3);
INSERT INTO SOP_TIPO_SOLICITUD (TIPO_SOLICITUD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_TIPO.NEXTVAL, 1, 'Mejora', 'Mejora de funcionalidad existente', 4);
INSERT INTO SOP_TIPO_SOLICITUD (TIPO_SOLICITUD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_TIPO.NEXTVAL, 1, 'Otro', 'Solicitud no clasificada', 5);

INSERT INTO SOP_PRIORIDAD (PRIORIDAD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, HORAS_SLA)
VALUES (SEQ_SOP_PRIOR.NEXTVAL, 1, 'Baja', 'Baja prioridad', 1, 72);
INSERT INTO SOP_PRIORIDAD (PRIORIDAD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, HORAS_SLA)
VALUES (SEQ_SOP_PRIOR.NEXTVAL, 1, 'Media', 'Prioridad media', 2, 48);
INSERT INTO SOP_PRIORIDAD (PRIORIDAD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, HORAS_SLA)
VALUES (SEQ_SOP_PRIOR.NEXTVAL, 1, 'Alta', 'Alta prioridad', 3, 24);
INSERT INTO SOP_PRIORIDAD (PRIORIDAD_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, HORAS_SLA)
VALUES (SEQ_SOP_PRIOR.NEXTVAL, 1, 'Critica', 'Prioridad critica', 4, 8);

INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'Nuevo', 'Ticket creado', 1, 0);
INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'Asignado', 'Ticket asignado', 2, 0);
INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'En proceso', 'Ticket en atencion', 3, 0);
INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'En espera del usuario', 'Pendiente por usuario', 4, 0);
INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'Resuelto', 'Ticket resuelto', 5, 0);
INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'Cerrado', 'Ticket cerrado', 6, 1);
INSERT INTO SOP_ESTADO (ESTADO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN, ES_FINAL)
VALUES (SEQ_SOP_EST.NEXTVAL, 1, 'Cancelado', 'Ticket cancelado', 7, 1);

INSERT INTO SOP_MODULO (MODULO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_MOD.NEXTVAL, 1, 'SIS', 'Sistema y seguridad', 1);
INSERT INTO SOP_MODULO (MODULO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_MOD.NEXTVAL, 1, 'RH', 'Recursos humanos', 2);
INSERT INTO SOP_MODULO (MODULO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_MOD.NEXTVAL, 1, 'Presupuesto', 'Modulo presupuesto', 3);
INSERT INTO SOP_MODULO (MODULO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_MOD.NEXTVAL, 1, 'Administracion', 'Modulo administrativo', 4);
INSERT INTO SOP_MODULO (MODULO_ID, CODIGO_EMPRESA, NOMBRE, DESCRIPCION, ORDEN)
VALUES (SEQ_SOP_MOD.NEXTVAL, 1, 'Otro', 'Otro modulo', 5);

COMMIT;
