CREATE OR REPLACE PROCEDURE SIS.SP_SOP_TKT_GET_ALL (
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_SearchText IN VARCHAR2,
  p_ESTADO_ID IN NUMBER,
  p_PRIORIDAD_ID IN NUMBER,
  p_TIPO_SOLICITUD_ID IN NUMBER,
  p_MODULO_ID IN NUMBER,
  p_RESPONSABLE_ID IN NUMBER,
  p_SOLICITANTE_ID IN NUMBER,
  p_FECHA_DESDE IN DATE,
  p_FECHA_HASTA IN DATE,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2,
  p_TotalRecords OUT NUMBER,
  p_TotalPages OUT NUMBER
) AS
  v_from NUMBER;
  v_to NUMBER;
BEGIN
  v_from := ((NVL(p_PageNumber, 1) - 1) * NVL(p_PageSize, 10)) + 1;
  v_to := NVL(p_PageNumber, 1) * NVL(p_PageSize, 10);

  SELECT COUNT(1) INTO p_TotalRecords
    FROM SIS.SOP_TICKET t
   WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND (p_ESTADO_ID IS NULL OR t.ESTADO_ID = p_ESTADO_ID)
     AND (p_PRIORIDAD_ID IS NULL OR t.PRIORIDAD_ID = p_PRIORIDAD_ID)
     AND (p_TIPO_SOLICITUD_ID IS NULL OR t.TIPO_SOLICITUD_ID = p_TIPO_SOLICITUD_ID)
     AND (p_MODULO_ID IS NULL OR t.MODULO_ID = p_MODULO_ID)
     AND (p_RESPONSABLE_ID IS NULL OR t.USUARIO_RESPONSABLE_ID = p_RESPONSABLE_ID)
     AND (p_SOLICITANTE_ID IS NULL OR t.USUARIO_SOLICITANTE_ID = p_SOLICITANTE_ID)
     AND (p_FECHA_DESDE IS NULL OR TRUNC(t.FECHA_CREACION) >= TRUNC(p_FECHA_DESDE))
     AND (p_FECHA_HASTA IS NULL OR TRUNC(t.FECHA_CREACION) <= TRUNC(p_FECHA_HASTA))
     AND (p_SearchText IS NULL OR UPPER(t.TICKET_NUMERO || ' ' || t.ASUNTO) LIKE '%' || UPPER(p_SearchText) || '%');

  p_TotalPages := CEIL(p_TotalRecords / NVL(p_PageSize, 10));

  OPEN p_ResultSet FOR
    SELECT *
      FROM (
        SELECT q.*, ROWNUM rn
          FROM (
            SELECT t.TICKET_ID, t.TICKET_NUMERO, t.USUARIO_SOLICITANTE_ID,
                   NVL(us.USUARIO, '') USUARIO_SOLICITANTE,
                   t.TIPO_SOLICITUD_ID, NVL(ts.NOMBRE, '') TIPO_SOLICITUD,
                   t.MODULO_ID, NVL(m.NOMBRE, '') MODULO,
                   t.ASUNTO, t.DESCRIPCION,
                   t.PRIORIDAD_ID, NVL(p.NOMBRE, '') PRIORIDAD,
                   t.ESTADO_ID, NVL(e.NOMBRE, '') ESTADO,
                   t.USUARIO_RESPONSABLE_ID, NVL(ur.USUARIO, '') USUARIO_RESPONSABLE,
                   t.FECHA_CREACION, t.FECHA_ASIGNACION, t.FECHA_PRIMERA_RESPUESTA,
                   t.FECHA_RESOLUCION, t.FECHA_CIERRE, NVL(t.OBSERVACION_RESOLUCION, '') OBSERVACION_RESOLUCION,
                   t.FECHA_VENCIMIENTO_SLA, t.CODIGO_EMPRESA
              FROM SIS.SOP_TICKET t
              LEFT JOIN SIS.SIS_USUARIOS us ON us.CODIGO_USUARIO = t.USUARIO_SOLICITANTE_ID
              LEFT JOIN SIS.SIS_USUARIOS ur ON ur.CODIGO_USUARIO = t.USUARIO_RESPONSABLE_ID
              LEFT JOIN SIS.SOP_TIPO_SOLICITUD ts ON ts.TIPO_SOLICITUD_ID = t.TIPO_SOLICITUD_ID
              LEFT JOIN SIS.SOP_PRIORIDAD p ON p.PRIORIDAD_ID = t.PRIORIDAD_ID
              LEFT JOIN SIS.SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
              LEFT JOIN SIS.SOP_MODULO m ON m.MODULO_ID = t.MODULO_ID
             WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
               AND (p_ESTADO_ID IS NULL OR t.ESTADO_ID = p_ESTADO_ID)
               AND (p_PRIORIDAD_ID IS NULL OR t.PRIORIDAD_ID = p_PRIORIDAD_ID)
               AND (p_TIPO_SOLICITUD_ID IS NULL OR t.TIPO_SOLICITUD_ID = p_TIPO_SOLICITUD_ID)
               AND (p_MODULO_ID IS NULL OR t.MODULO_ID = p_MODULO_ID)
               AND (p_RESPONSABLE_ID IS NULL OR t.USUARIO_RESPONSABLE_ID = p_RESPONSABLE_ID)
               AND (p_SOLICITANTE_ID IS NULL OR t.USUARIO_SOLICITANTE_ID = p_SOLICITANTE_ID)
               AND (p_FECHA_DESDE IS NULL OR TRUNC(t.FECHA_CREACION) >= TRUNC(p_FECHA_DESDE))
               AND (p_FECHA_HASTA IS NULL OR TRUNC(t.FECHA_CREACION) <= TRUNC(p_FECHA_HASTA))
               AND (p_SearchText IS NULL OR UPPER(t.TICKET_NUMERO || ' ' || t.ASUNTO) LIKE '%' || UPPER(p_SearchText) || '%')
             ORDER BY t.FECHA_CREACION DESC
          ) q
         WHERE ROWNUM <= v_to
      )
     WHERE rn >= v_from;

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_TotalRecords := 0;
    p_TotalPages := 0;
    p_Message := SQLERRM;
    OPEN p_ResultSet FOR
      SELECT CAST(NULL AS NUMBER) TICKET_ID,
             CAST(NULL AS VARCHAR2(30)) TICKET_NUMERO,
             CAST(NULL AS NUMBER) USUARIO_SOLICITANTE_ID,
             CAST(NULL AS VARCHAR2(200)) USUARIO_SOLICITANTE,
             CAST(NULL AS NUMBER) TIPO_SOLICITUD_ID,
             CAST(NULL AS VARCHAR2(100)) TIPO_SOLICITUD,
             CAST(NULL AS NUMBER) MODULO_ID,
             CAST(NULL AS VARCHAR2(100)) MODULO,
             CAST(NULL AS VARCHAR2(200)) ASUNTO,
             CAST(NULL AS VARCHAR2(4000)) DESCRIPCION,
             CAST(NULL AS NUMBER) PRIORIDAD_ID,
             CAST(NULL AS VARCHAR2(100)) PRIORIDAD,
             CAST(NULL AS NUMBER) ESTADO_ID,
             CAST(NULL AS VARCHAR2(100)) ESTADO,
             CAST(NULL AS NUMBER) USUARIO_RESPONSABLE_ID,
             CAST(NULL AS VARCHAR2(200)) USUARIO_RESPONSABLE,
             CAST(NULL AS DATE) FECHA_CREACION,
             CAST(NULL AS DATE) FECHA_ASIGNACION,
             CAST(NULL AS DATE) FECHA_PRIMERA_RESPUESTA,
             CAST(NULL AS DATE) FECHA_RESOLUCION,
             CAST(NULL AS DATE) FECHA_CIERRE,
             CAST(NULL AS VARCHAR2(4000)) OBSERVACION_RESOLUCION,
             CAST(NULL AS DATE) FECHA_VENCIMIENTO_SLA,
             CAST(NULL AS NUMBER) CODIGO_EMPRESA
        FROM DUAL
       WHERE 1 = 0;
END;
/

SHOW ERRORS PROCEDURE SIS.SP_SOP_TKT_GET_ALL;

SELECT owner, object_name, object_type, status
  FROM all_objects
 WHERE owner = 'SIS'
   AND object_name = 'SP_SOP_TKT_GET_ALL';
