CREATE OR REPLACE PROCEDURE SP_SOP_DASH_SUMMARY (
  p_FECHA_DESDE IN DATE,
  p_FECHA_HASTA IN DATE,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT COUNT(1) TOTAL_TICKETS,
           NVL(SUM(CASE WHEN NVL(e.ES_FINAL, 0) = 0 THEN 1 ELSE 0 END), 0) TICKETS_ABIERTOS,
           NVL(SUM(CASE WHEN UPPER(e.NOMBRE) = 'CERRADO' THEN 1 ELSE 0 END), 0) TICKETS_CERRADOS,
           NVL(SUM(CASE WHEN UPPER(p.NOMBRE) = 'CRITICA' THEN 1 ELSE 0 END), 0) TICKETS_CRITICOS,
           NVL(SUM(CASE WHEN NVL(e.ES_FINAL, 0) = 0 AND t.FECHA_VENCIMIENTO_SLA < SYSDATE THEN 1 ELSE 0 END), 0) TICKETS_VENCIDOS,
           NVL(SUM(CASE WHEN t.USUARIO_RESPONSABLE_ID IS NULL THEN 1 ELSE 0 END), 0) TICKETS_SIN_ASIGNAR,
           ROUND(NVL(AVG(CASE WHEN t.FECHA_RESOLUCION IS NOT NULL THEN t.FECHA_RESOLUCION - t.FECHA_CREACION END), 0), 4) TIEMPO_PROMEDIO_RESOLUCION
      FROM SOP_TICKET t
      JOIN SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
      JOIN SOP_PRIORIDAD p ON p.PRIORIDAD_ID = t.PRIORIDAD_ID
     WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND (p_FECHA_DESDE IS NULL OR TRUNC(t.FECHA_CREACION) >= TRUNC(p_FECHA_DESDE))
       AND (p_FECHA_HASTA IS NULL OR TRUNC(t.FECHA_CREACION) <= TRUNC(p_FECHA_HASTA));

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
    OPEN p_ResultSet FOR
      SELECT 0 TOTAL_TICKETS,
             0 TICKETS_ABIERTOS,
             0 TICKETS_CERRADOS,
             0 TICKETS_CRITICOS,
             0 TICKETS_VENCIDOS,
             0 TICKETS_SIN_ASIGNAR,
             0 TIEMPO_PROMEDIO_RESOLUCION
        FROM DUAL;
END;
/
