CREATE OR REPLACE PROCEDURE SP_SOP_TKT_INS (
  p_USUARIO_SOLICITANTE_ID IN NUMBER,
  p_TIPO_SOLICITUD_ID IN NUMBER,
  p_MODULO_ID IN NUMBER,
  p_ASUNTO IN VARCHAR2,
  p_DESCRIPCION IN VARCHAR2,
  p_PRIORIDAD_ID IN NUMBER,
  p_CREATED_BY IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_TICKET_ID_OUT OUT NUMBER,
  p_Message OUT VARCHAR2
) AS
  v_estado NUMBER;
  v_horas NUMBER;
BEGIN
  SELECT ESTADO_ID INTO v_estado
    FROM SOP_ESTADO
   WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND UPPER(NOMBRE) = 'NUEVO'
     AND ROWNUM = 1;

  SELECT NVL(HORAS_SLA, 48) INTO v_horas
    FROM SOP_PRIORIDAD
   WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND PRIORIDAD_ID = p_PRIORIDAD_ID;

  p_TICKET_ID_OUT := SEQ_SOP_TKT.NEXTVAL;

  INSERT INTO SOP_TICKET (
    TICKET_ID, CODIGO_EMPRESA, TICKET_NUMERO, USUARIO_SOLICITANTE_ID,
    TIPO_SOLICITUD_ID, MODULO_ID, ASUNTO, DESCRIPCION, PRIORIDAD_ID,
    ESTADO_ID, FECHA_CREACION, FECHA_VENCIMIENTO_SLA, CREATED_BY, CREATED_AT
  ) VALUES (
    p_TICKET_ID_OUT, p_CODIGO_EMPRESA, 'SOP-' || TO_CHAR(p_TICKET_ID_OUT),
    p_USUARIO_SOLICITANTE_ID, p_TIPO_SOLICITUD_ID, p_MODULO_ID,
    p_ASUNTO, p_DESCRIPCION, p_PRIORIDAD_ID, v_estado, SYSDATE,
    SYSDATE + (v_horas / 24), p_CREATED_BY, SYSDATE
  );

  INSERT INTO SOP_TICKET_HISTORIAL (
    HISTORIAL_ID, CODIGO_EMPRESA, TICKET_ID, TIPO_CAMBIO, CAMPO,
    VALOR_ANTERIOR, VALOR_NUEVO, COMENTARIO, USUARIO_ID
  ) VALUES (
    SEQ_SOP_HIST.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID_OUT, 'CREADO',
    'ESTADO_ID', NULL, TO_CHAR(v_estado), 'Ticket creado', p_CREATED_BY
  );

  INSERT INTO SOP_TICKET_NOTIF (
    NOTIF_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_DESTINO_ID, TIPO_DESTINO,
    EVENTO, TITULO, MENSAJE, CANAL
  ) VALUES (
    SEQ_SOP_NOTIF.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID_OUT,
    p_USUARIO_SOLICITANTE_ID, 'SOLICITANTE', 'CREADO',
    'Ticket creado', 'Su ticket ' || 'SOP-' || TO_CHAR(p_TICKET_ID_OUT) || ' fue creado.', 'INTERNA'
  );

  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  )
  SELECT SEQ_EMAIL_Q.NEXTVAL, p_CODIGO_EMPRESA, 'SOPORTE', p_TICKET_ID_OUT,
         u.EMAIL, u.USUARIO, 'Ticket creado',
         '<p>Su ticket SOP-' || TO_CHAR(p_TICKET_ID_OUT) || ' fue creado.</p>',
         'Su ticket SOP-' || TO_CHAR(p_TICKET_ID_OUT) || ' fue creado.',
         SYSDATE
    FROM SIS_USUARIOS u
   WHERE u.CODIGO_USUARIO = p_USUARIO_SOLICITANTE_ID
     AND u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND NVL(u.RECIBE_EMAIL, 1) = 1
     AND u.EMAIL IS NOT NULL;

  p_Message := 'Success';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_TICKET_ID_OUT := 0;
    p_Message := 'No se encontraron catalogos iniciales para crear el ticket.';
  WHEN OTHERS THEN
    p_TICKET_ID_OUT := 0;
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_TKT_GET_ALL (
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_SearchText IN VARCHAR2,
  p_ESTADO_ID IN NUMBER,
  p_PRIORIDAD_ID IN NUMBER,
  p_TIPO_SOLICITUD_ID IN NUMBER,
  p_MODULO_ID IN NUMBER,
  p_RESPONSABLE_ID IN NUMBER,
  p_SOLICITANTE_ID IN NUMBER,
  p_FECHA_DESDE IN DATE,
  p_FECHA_HASTA IN DATE,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2,
  p_TotalRecords OUT NUMBER,
  p_TotalPages OUT NUMBER
) AS
  v_from NUMBER;
  v_to NUMBER;
BEGIN
  v_from := ((NVL(p_PageNumber, 1) - 1) * NVL(p_PageSize, 10)) + 1;
  v_to := NVL(p_PageNumber, 1) * NVL(p_PageSize, 10);

  SELECT COUNT(1) INTO p_TotalRecords
    FROM SOP_TICKET t
   WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND (p_ESTADO_ID IS NULL OR t.ESTADO_ID = p_ESTADO_ID)
     AND (p_PRIORIDAD_ID IS NULL OR t.PRIORIDAD_ID = p_PRIORIDAD_ID)
     AND (p_TIPO_SOLICITUD_ID IS NULL OR t.TIPO_SOLICITUD_ID = p_TIPO_SOLICITUD_ID)
     AND (p_MODULO_ID IS NULL OR t.MODULO_ID = p_MODULO_ID)
     AND (p_RESPONSABLE_ID IS NULL OR t.USUARIO_RESPONSABLE_ID = p_RESPONSABLE_ID)
     AND (p_SOLICITANTE_ID IS NULL OR t.USUARIO_SOLICITANTE_ID = p_SOLICITANTE_ID)
     AND (p_FECHA_DESDE IS NULL OR TRUNC(t.FECHA_CREACION) >= TRUNC(p_FECHA_DESDE))
     AND (p_FECHA_HASTA IS NULL OR TRUNC(t.FECHA_CREACION) <= TRUNC(p_FECHA_HASTA))
     AND (p_SearchText IS NULL OR UPPER(t.TICKET_NUMERO || ' ' || t.ASUNTO) LIKE '%' || UPPER(p_SearchText) || '%');

  p_TotalPages := CEIL(p_TotalRecords / NVL(p_PageSize, 10));

  OPEN p_ResultSet FOR
    SELECT *
      FROM (
        SELECT q.*, ROWNUM rn
          FROM (
            SELECT t.TICKET_ID, t.TICKET_NUMERO, t.USUARIO_SOLICITANTE_ID,
                   NVL(us.USUARIO, '') USUARIO_SOLICITANTE,
                   t.TIPO_SOLICITUD_ID, NVL(ts.NOMBRE, '') TIPO_SOLICITUD,
                   t.MODULO_ID, NVL(m.NOMBRE, '') MODULO,
                   t.ASUNTO, t.DESCRIPCION,
                   t.PRIORIDAD_ID, NVL(p.NOMBRE, '') PRIORIDAD,
                   t.ESTADO_ID, NVL(e.NOMBRE, '') ESTADO,
                   t.USUARIO_RESPONSABLE_ID, NVL(ur.USUARIO, '') USUARIO_RESPONSABLE,
                   t.FECHA_CREACION, t.FECHA_ASIGNACION, t.FECHA_PRIMERA_RESPUESTA,
                   t.FECHA_RESOLUCION, t.FECHA_CIERRE, NVL(t.OBSERVACION_RESOLUCION, '') OBSERVACION_RESOLUCION,
                   t.FECHA_VENCIMIENTO_SLA, t.CODIGO_EMPRESA
              FROM SOP_TICKET t
              LEFT JOIN SIS_USUARIOS us ON us.CODIGO_USUARIO = t.USUARIO_SOLICITANTE_ID
              LEFT JOIN SIS_USUARIOS ur ON ur.CODIGO_USUARIO = t.USUARIO_RESPONSABLE_ID
              LEFT JOIN SOP_TIPO_SOLICITUD ts ON ts.TIPO_SOLICITUD_ID = t.TIPO_SOLICITUD_ID
              LEFT JOIN SOP_PRIORIDAD p ON p.PRIORIDAD_ID = t.PRIORIDAD_ID
              LEFT JOIN SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
              LEFT JOIN SOP_MODULO m ON m.MODULO_ID = t.MODULO_ID
             WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
               AND (p_ESTADO_ID IS NULL OR t.ESTADO_ID = p_ESTADO_ID)
               AND (p_PRIORIDAD_ID IS NULL OR t.PRIORIDAD_ID = p_PRIORIDAD_ID)
               AND (p_TIPO_SOLICITUD_ID IS NULL OR t.TIPO_SOLICITUD_ID = p_TIPO_SOLICITUD_ID)
               AND (p_MODULO_ID IS NULL OR t.MODULO_ID = p_MODULO_ID)
               AND (p_RESPONSABLE_ID IS NULL OR t.USUARIO_RESPONSABLE_ID = p_RESPONSABLE_ID)
               AND (p_SOLICITANTE_ID IS NULL OR t.USUARIO_SOLICITANTE_ID = p_SOLICITANTE_ID)
               AND (p_FECHA_DESDE IS NULL OR TRUNC(t.FECHA_CREACION) >= TRUNC(p_FECHA_DESDE))
               AND (p_FECHA_HASTA IS NULL OR TRUNC(t.FECHA_CREACION) <= TRUNC(p_FECHA_HASTA))
               AND (p_SearchText IS NULL OR UPPER(t.TICKET_NUMERO || ' ' || t.ASUNTO) LIKE '%' || UPPER(p_SearchText) || '%')
             ORDER BY t.FECHA_CREACION DESC
          ) q
         WHERE ROWNUM <= v_to
      )
     WHERE rn >= v_from;

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_TotalRecords := 0;
    p_TotalPages := 0;
    p_Message := SQLERRM;
    OPEN p_ResultSet FOR
      SELECT CAST(NULL AS NUMBER) TICKET_ID,
             CAST(NULL AS VARCHAR2(30)) TICKET_NUMERO,
             CAST(NULL AS NUMBER) USUARIO_SOLICITANTE_ID,
             CAST(NULL AS VARCHAR2(200)) USUARIO_SOLICITANTE,
             CAST(NULL AS NUMBER) TIPO_SOLICITUD_ID,
             CAST(NULL AS VARCHAR2(100)) TIPO_SOLICITUD,
             CAST(NULL AS NUMBER) MODULO_ID,
             CAST(NULL AS VARCHAR2(100)) MODULO,
             CAST(NULL AS VARCHAR2(200)) ASUNTO,
             CAST(NULL AS VARCHAR2(4000)) DESCRIPCION,
             CAST(NULL AS NUMBER) PRIORIDAD_ID,
             CAST(NULL AS VARCHAR2(100)) PRIORIDAD,
             CAST(NULL AS NUMBER) ESTADO_ID,
             CAST(NULL AS VARCHAR2(100)) ESTADO,
             CAST(NULL AS NUMBER) USUARIO_RESPONSABLE_ID,
             CAST(NULL AS VARCHAR2(200)) USUARIO_RESPONSABLE,
             CAST(NULL AS DATE) FECHA_CREACION,
             CAST(NULL AS DATE) FECHA_ASIGNACION,
             CAST(NULL AS DATE) FECHA_PRIMERA_RESPUESTA,
             CAST(NULL AS DATE) FECHA_RESOLUCION,
             CAST(NULL AS DATE) FECHA_CIERRE,
             CAST(NULL AS VARCHAR2(4000)) OBSERVACION_RESOLUCION,
             CAST(NULL AS DATE) FECHA_VENCIMIENTO_SLA,
             CAST(NULL AS NUMBER) CODIGO_EMPRESA
        FROM DUAL
       WHERE 1 = 0;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_TKT_GET_ID (
  p_TICKET_ID IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT t.TICKET_ID, t.TICKET_NUMERO, t.USUARIO_SOLICITANTE_ID,
           NVL(us.USUARIO, '') USUARIO_SOLICITANTE,
           t.TIPO_SOLICITUD_ID, NVL(ts.NOMBRE, '') TIPO_SOLICITUD,
           t.MODULO_ID, NVL(m.NOMBRE, '') MODULO,
           t.ASUNTO, t.DESCRIPCION,
           t.PRIORIDAD_ID, NVL(p.NOMBRE, '') PRIORIDAD,
           t.ESTADO_ID, NVL(e.NOMBRE, '') ESTADO,
           t.USUARIO_RESPONSABLE_ID, NVL(ur.USUARIO, '') USUARIO_RESPONSABLE,
           t.FECHA_CREACION, t.FECHA_ASIGNACION, t.FECHA_PRIMERA_RESPUESTA,
           t.FECHA_RESOLUCION, t.FECHA_CIERRE, NVL(t.OBSERVACION_RESOLUCION, '') OBSERVACION_RESOLUCION,
           t.FECHA_VENCIMIENTO_SLA, t.CODIGO_EMPRESA
      FROM SOP_TICKET t
      LEFT JOIN SIS_USUARIOS us ON us.CODIGO_USUARIO = t.USUARIO_SOLICITANTE_ID
      LEFT JOIN SIS_USUARIOS ur ON ur.CODIGO_USUARIO = t.USUARIO_RESPONSABLE_ID
      LEFT JOIN SOP_TIPO_SOLICITUD ts ON ts.TIPO_SOLICITUD_ID = t.TIPO_SOLICITUD_ID
      LEFT JOIN SOP_PRIORIDAD p ON p.PRIORIDAD_ID = t.PRIORIDAD_ID
      LEFT JOIN SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
      LEFT JOIN SOP_MODULO m ON m.MODULO_ID = t.MODULO_ID
     WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND t.TICKET_ID = p_TICKET_ID;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_TKT_ASSIGN (
  p_TICKET_ID IN NUMBER,
  p_USUARIO_RESPONSABLE_ID IN NUMBER,
  p_UPDATED_BY IN NUMBER,
  p_COMENTARIO IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
  v_old NUMBER;
  v_analista NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_analista
    FROM SIS_USUARIOS
   WHERE CODIGO_USUARIO = p_USUARIO_RESPONSABLE_ID
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND NVL(STATUS, 'A') IN ('1', 'A')
     AND NVL(ES_ANALISTA_SOPORTE, 0) = 1;

  IF v_analista = 0 THEN
    p_Message := 'El responsable seleccionado no esta marcado como analista de soporte.';
    RETURN;
  END IF;

  SELECT USUARIO_RESPONSABLE_ID INTO v_old
    FROM SOP_TICKET
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  UPDATE SOP_TICKET
     SET USUARIO_RESPONSABLE_ID = p_USUARIO_RESPONSABLE_ID,
         FECHA_ASIGNACION = NVL(FECHA_ASIGNACION, SYSDATE),
         UPDATED_BY = p_UPDATED_BY,
         UPDATED_AT = SYSDATE
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  INSERT INTO SOP_TICKET_HISTORIAL
    (HISTORIAL_ID, CODIGO_EMPRESA, TICKET_ID, TIPO_CAMBIO, CAMPO, VALOR_ANTERIOR, VALOR_NUEVO, COMENTARIO, USUARIO_ID)
  VALUES
    (SEQ_SOP_HIST.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, 'ASIGNACION', 'USUARIO_RESPONSABLE_ID', TO_CHAR(v_old), TO_CHAR(p_USUARIO_RESPONSABLE_ID), p_COMENTARIO, p_UPDATED_BY);

  INSERT INTO SOP_TICKET_NOTIF
    (NOTIF_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_DESTINO_ID, TIPO_DESTINO, EVENTO, TITULO, MENSAJE, CANAL)
  VALUES
    (SEQ_SOP_NOTIF.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, p_USUARIO_RESPONSABLE_ID, 'RESPONSABLE', 'ASIGNADO', 'Ticket asignado', 'Se le asigno un ticket de soporte.', 'INTERNA');

  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  )
  SELECT SEQ_EMAIL_Q.NEXTVAL, p_CODIGO_EMPRESA, 'SOPORTE', p_TICKET_ID,
         u.EMAIL, u.USUARIO, 'Ticket asignado',
         '<p>Se le asigno un ticket de soporte.</p>',
         'Se le asigno un ticket de soporte.',
         SYSDATE
    FROM SIS_USUARIOS u
   WHERE u.CODIGO_USUARIO = p_USUARIO_RESPONSABLE_ID
     AND u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND NVL(u.RECIBE_EMAIL, 1) = 1
     AND u.EMAIL IS NOT NULL;

  p_Message := 'Success';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_Message := 'No se encontró el ticket indicado.';
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_TKT_STATUS_UPD (
  p_TICKET_ID IN NUMBER,
  p_ESTADO_ID IN NUMBER,
  p_UPDATED_BY IN NUMBER,
  p_COMENTARIO IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
  v_old NUMBER;
  v_solicitante NUMBER;
  v_responsable NUMBER;
  v_estado_nombre VARCHAR2(80);
  v_evento VARCHAR2(30);
  v_titulo VARCHAR2(200);
BEGIN
  SELECT t.ESTADO_ID, t.USUARIO_SOLICITANTE_ID, t.USUARIO_RESPONSABLE_ID,
         UPPER(NVL(e.NOMBRE, ''))
    INTO v_old, v_solicitante, v_responsable, v_estado_nombre
    FROM SOP_TICKET t
    LEFT JOIN SOP_ESTADO e ON e.ESTADO_ID = p_ESTADO_ID AND e.CODIGO_EMPRESA = p_CODIGO_EMPRESA
   WHERE t.TICKET_ID = p_TICKET_ID AND t.CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  IF v_estado_nombre LIKE '%RESUELT%' THEN
    v_evento := 'RESUELTO';
    v_titulo := 'Ticket resuelto';
  ELSIF v_estado_nombre LIKE '%REABIERT%' THEN
    v_evento := 'REABIERTO';
    v_titulo := 'Ticket reabierto';
  ELSIF v_estado_nombre LIKE '%CANCEL%' THEN
    v_evento := 'CANCELADO';
    v_titulo := 'Ticket cancelado';
  ELSE
    v_evento := 'ESTADO';
    v_titulo := 'Estado actualizado';
  END IF;

  IF v_evento = 'RESUELTO' THEN
    UPDATE SOP_TICKET
       SET FECHA_RESOLUCION = NVL(FECHA_RESOLUCION, SYSDATE)
     WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;
  END IF;

  SELECT ESTADO_ID INTO v_old
    FROM SOP_TICKET
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  UPDATE SOP_TICKET
     SET ESTADO_ID = p_ESTADO_ID,
         UPDATED_BY = p_UPDATED_BY,
         UPDATED_AT = SYSDATE
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  INSERT INTO SOP_TICKET_HISTORIAL
    (HISTORIAL_ID, CODIGO_EMPRESA, TICKET_ID, TIPO_CAMBIO, CAMPO, VALOR_ANTERIOR, VALOR_NUEVO, COMENTARIO, USUARIO_ID)
  VALUES
    (SEQ_SOP_HIST.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, 'ESTADO', 'ESTADO_ID', TO_CHAR(v_old), TO_CHAR(p_ESTADO_ID), p_COMENTARIO, p_UPDATED_BY);

  INSERT INTO SOP_TICKET_NOTIF
    (NOTIF_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_DESTINO_ID, TIPO_DESTINO, EVENTO, TITULO, MENSAJE, CANAL)
  SELECT SEQ_SOP_NOTIF.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, destino.USUARIO_ID,
         destino.TIPO_DESTINO, v_evento, v_titulo,
         'El estado del ticket fue actualizado.', 'INTERNA'
    FROM (
      SELECT v_solicitante USUARIO_ID, 'SOLICITANTE' TIPO_DESTINO FROM DUAL
      UNION
      SELECT v_responsable USUARIO_ID, 'RESPONSABLE' TIPO_DESTINO FROM DUAL
    ) destino
   WHERE destino.USUARIO_ID IS NOT NULL
     AND destino.USUARIO_ID <> p_UPDATED_BY;

  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  )
  SELECT SEQ_EMAIL_Q.NEXTVAL, p_CODIGO_EMPRESA, 'SOPORTE', p_TICKET_ID,
         u.EMAIL, u.USUARIO, v_titulo,
         '<p>El estado del ticket fue actualizado.</p>',
         'El estado del ticket fue actualizado.',
         SYSDATE
    FROM SIS_USUARIOS u
   WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND u.CODIGO_USUARIO IN (v_solicitante, v_responsable)
     AND u.CODIGO_USUARIO <> p_UPDATED_BY
     AND NVL(u.RECIBE_EMAIL, 1) = 1
     AND u.EMAIL IS NOT NULL;

  p_Message := 'Success';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_Message := 'No se encontró el ticket indicado.';
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_TKT_CLOSE (
  p_TICKET_ID IN NUMBER,
  p_UPDATED_BY IN NUMBER,
  p_OBSERVACION_RESOLUCION IN VARCHAR2,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
  v_estado NUMBER;
  v_solicitante NUMBER;
  v_responsable NUMBER;
BEGIN
  SELECT ESTADO_ID INTO v_estado
    FROM SOP_ESTADO
   WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND UPPER(NOMBRE) = 'CERRADO'
     AND ROWNUM = 1;

  SELECT USUARIO_SOLICITANTE_ID, USUARIO_RESPONSABLE_ID
    INTO v_solicitante, v_responsable
    FROM SOP_TICKET
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  UPDATE SOP_TICKET
     SET ESTADO_ID = v_estado,
         FECHA_CIERRE = SYSDATE,
         FECHA_RESOLUCION = NVL(FECHA_RESOLUCION, SYSDATE),
         OBSERVACION_RESOLUCION = p_OBSERVACION_RESOLUCION,
         UPDATED_BY = p_UPDATED_BY,
         UPDATED_AT = SYSDATE
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  INSERT INTO SOP_TICKET_HISTORIAL
    (HISTORIAL_ID, CODIGO_EMPRESA, TICKET_ID, TIPO_CAMBIO, CAMPO, VALOR_NUEVO, COMENTARIO, USUARIO_ID)
  VALUES
    (SEQ_SOP_HIST.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, 'CIERRE', 'ESTADO_ID', TO_CHAR(v_estado), p_OBSERVACION_RESOLUCION, p_UPDATED_BY);

  INSERT INTO SOP_TICKET_NOTIF
    (NOTIF_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_DESTINO_ID, TIPO_DESTINO, EVENTO, TITULO, MENSAJE, CANAL)
  SELECT SEQ_SOP_NOTIF.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, destino.USUARIO_ID,
         destino.TIPO_DESTINO, 'CERRADO', 'Ticket cerrado',
         'El ticket fue cerrado.', 'INTERNA'
    FROM (
      SELECT v_solicitante USUARIO_ID, 'SOLICITANTE' TIPO_DESTINO FROM DUAL
      UNION
      SELECT v_responsable USUARIO_ID, 'RESPONSABLE' TIPO_DESTINO FROM DUAL
    ) destino
   WHERE destino.USUARIO_ID IS NOT NULL
     AND destino.USUARIO_ID <> p_UPDATED_BY;

  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  )
  SELECT SEQ_EMAIL_Q.NEXTVAL, p_CODIGO_EMPRESA, 'SOPORTE', p_TICKET_ID,
         u.EMAIL, u.USUARIO, 'Ticket cerrado',
         '<p>El ticket fue cerrado.</p>',
         'El ticket fue cerrado.',
         SYSDATE
    FROM SIS_USUARIOS u
   WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND u.CODIGO_USUARIO IN (v_solicitante, v_responsable)
     AND u.CODIGO_USUARIO <> p_UPDATED_BY
     AND NVL(u.RECIBE_EMAIL, 1) = 1
     AND u.EMAIL IS NOT NULL;

  p_Message := 'Success';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_Message := 'No se encontró el estado Cerrado.';
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_COMM_INS (
  p_TICKET_ID IN NUMBER,
  p_USUARIO_ID IN NUMBER,
  p_COMENTARIO IN VARCHAR2,
  p_ES_INTERNO IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_COMENTARIO_ID_OUT OUT NUMBER,
  p_Message OUT VARCHAR2
) AS
  v_solicitante NUMBER;
  v_responsable NUMBER;
BEGIN
  SELECT USUARIO_SOLICITANTE_ID, USUARIO_RESPONSABLE_ID
    INTO v_solicitante, v_responsable
    FROM SOP_TICKET
   WHERE TICKET_ID = p_TICKET_ID AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;

  p_COMENTARIO_ID_OUT := SEQ_SOP_COMM.NEXTVAL;
  INSERT INTO SOP_TICKET_COMENTARIO
    (COMENTARIO_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_ID, COMENTARIO, ES_INTERNO)
  VALUES
    (p_COMENTARIO_ID_OUT, p_CODIGO_EMPRESA, p_TICKET_ID, p_USUARIO_ID, p_COMENTARIO, NVL(p_ES_INTERNO, 0));

  INSERT INTO SOP_TICKET_HISTORIAL
    (HISTORIAL_ID, CODIGO_EMPRESA, TICKET_ID, TIPO_CAMBIO, CAMPO, VALOR_NUEVO, COMENTARIO, USUARIO_ID)
  VALUES
    (SEQ_SOP_HIST.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, 'COMENTARIO', 'COMENTARIO_ID', TO_CHAR(p_COMENTARIO_ID_OUT), p_COMENTARIO, p_USUARIO_ID);

  INSERT INTO SOP_TICKET_NOTIF
    (NOTIF_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_DESTINO_ID, TIPO_DESTINO, EVENTO, TITULO, MENSAJE, CANAL)
  SELECT SEQ_SOP_NOTIF.NEXTVAL, p_CODIGO_EMPRESA, p_TICKET_ID, destino.USUARIO_ID,
         destino.TIPO_DESTINO, 'COMENTADO', 'Nuevo comentario',
         'El ticket tiene un nuevo comentario.', 'INTERNA'
    FROM (
      SELECT v_solicitante USUARIO_ID, 'SOLICITANTE' TIPO_DESTINO FROM DUAL
      UNION
      SELECT v_responsable USUARIO_ID, 'RESPONSABLE' TIPO_DESTINO FROM DUAL
    ) destino
   WHERE destino.USUARIO_ID IS NOT NULL
     AND destino.USUARIO_ID <> p_USUARIO_ID
     AND NVL(p_ES_INTERNO, 0) = 0;

  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  )
  SELECT SEQ_EMAIL_Q.NEXTVAL, p_CODIGO_EMPRESA, 'SOPORTE', p_TICKET_ID,
         u.EMAIL, u.USUARIO, 'Nuevo comentario en ticket',
         '<p>El ticket tiene un nuevo comentario.</p>',
         'El ticket tiene un nuevo comentario.',
         SYSDATE
    FROM SIS_USUARIOS u
   WHERE u.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND u.CODIGO_USUARIO IN (v_solicitante, v_responsable)
     AND u.CODIGO_USUARIO <> p_USUARIO_ID
     AND NVL(p_ES_INTERNO, 0) = 0
     AND NVL(u.RECIBE_EMAIL, 1) = 1
     AND u.EMAIL IS NOT NULL;

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_COMENTARIO_ID_OUT := 0;
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_COMM_GET_TKT (
  p_TICKET_ID IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT c.COMENTARIO_ID, c.TICKET_ID, c.USUARIO_ID, NVL(u.USUARIO, '') USUARIO,
           c.COMENTARIO, c.ES_INTERNO, c.FECHA_COMENTARIO
      FROM SOP_TICKET_COMENTARIO c
      LEFT JOIN SIS_USUARIOS u ON u.CODIGO_USUARIO = c.USUARIO_ID
     WHERE c.CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND c.TICKET_ID = p_TICKET_ID
     ORDER BY c.FECHA_COMENTARIO;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_HIST_GET_TKT (
  p_TICKET_ID IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT HISTORIAL_ID, TICKET_ID, TIPO_CAMBIO, NVL(CAMPO, '') CAMPO,
           NVL(VALOR_ANTERIOR, '') VALOR_ANTERIOR,
           NVL(VALOR_NUEVO, '') VALOR_NUEVO,
           NVL(COMENTARIO, '') COMENTARIO,
           USUARIO_ID, FECHA_CAMBIO
      FROM SOP_TICKET_HISTORIAL
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND TICKET_ID = p_TICKET_ID
     ORDER BY FECHA_CAMBIO;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_ATT_INS (
  p_TICKET_ID IN NUMBER,
  p_NOMBRE_ORIGINAL IN VARCHAR2,
  p_IDENTIFICADOR_ARCHIVO IN VARCHAR2,
  p_RUTA_ARCHIVO IN VARCHAR2,
  p_MIME_TYPE IN VARCHAR2,
  p_TAMANO_BYTES IN NUMBER,
  p_USUARIO_CARGA_ID IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ADJUNTO_ID_OUT OUT NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  p_ADJUNTO_ID_OUT := SEQ_SOP_ATT.NEXTVAL;
  INSERT INTO SOP_TICKET_ADJUNTO (
    ADJUNTO_ID, CODIGO_EMPRESA, TICKET_ID, NOMBRE_ORIGINAL,
    IDENTIFICADOR_ARCHIVO, RUTA_ARCHIVO, MIME_TYPE, TAMANO_BYTES,
    USUARIO_CARGA_ID
  ) VALUES (
    p_ADJUNTO_ID_OUT, p_CODIGO_EMPRESA, p_TICKET_ID, p_NOMBRE_ORIGINAL,
    p_IDENTIFICADOR_ARCHIVO, p_RUTA_ARCHIVO, p_MIME_TYPE, p_TAMANO_BYTES,
    p_USUARIO_CARGA_ID
  );
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_ADJUNTO_ID_OUT := 0;
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_ATT_GET_TKT (
  p_TICKET_ID IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT ADJUNTO_ID, TICKET_ID, NOMBRE_ORIGINAL,
           NVL(IDENTIFICADOR_ARCHIVO, '') IDENTIFICADOR_ARCHIVO,
           NVL(RUTA_ARCHIVO, '') RUTA_ARCHIVO,
           NVL(MIME_TYPE, '') MIME_TYPE,
           NVL(TAMANO_BYTES, 0) TAMANO_BYTES,
           USUARIO_CARGA_ID, FECHA_CARGA, ACTIVO
      FROM SOP_TICKET_ADJUNTO
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND TICKET_ID = p_TICKET_ID
       AND ACTIVO = 1
     ORDER BY FECHA_CARGA DESC;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_TYPE_GET_ALL (
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT TIPO_SOLICITUD_ID ID, NOMBRE, NVL(DESCRIPCION, '') DESCRIPCION, ORDEN, ACTIVO
      FROM SOP_TIPO_SOLICITUD
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     ORDER BY ORDEN, NOMBRE;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_PRIOR_GET_ALL (
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT PRIORIDAD_ID ID, NOMBRE, NVL(DESCRIPCION, '') DESCRIPCION, ORDEN, ACTIVO
      FROM SOP_PRIORIDAD
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     ORDER BY ORDEN, NOMBRE;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_STATUS_GET_ALL (
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT ESTADO_ID ID, NOMBRE, NVL(DESCRIPCION, '') DESCRIPCION, ORDEN, ACTIVO
      FROM SOP_ESTADO
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     ORDER BY ORDEN, NOMBRE;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_MODULE_GET_ALL (
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT MODULO_ID ID, NOMBRE, NVL(DESCRIPCION, '') DESCRIPCION, ORDEN, ACTIVO
      FROM SOP_MODULO
     WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
     ORDER BY ORDEN, NOMBRE;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_NOTIF_GET_USR (
  p_USUARIO_ID IN NUMBER,
  p_PageSize IN NUMBER,
  p_PageNumber IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT *
      FROM (
        SELECT NOTIF_ID, TICKET_ID, USUARIO_DESTINO_ID, EVENTO, TITULO, MENSAJE,
               CANAL, LEIDA, FECHA_CREACION
          FROM SOP_TICKET_NOTIF
         WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
           AND USUARIO_DESTINO_ID = p_USUARIO_ID
         ORDER BY FECHA_CREACION DESC
      )
     WHERE ROWNUM <= NVL(p_PageSize, 10);
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_NOTIF_MARK_READ (
  p_NOTIF_ID IN NUMBER,
  p_USUARIO_ID IN NUMBER,
  p_CODIGO_EMPRESA IN NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  UPDATE SOP_TICKET_NOTIF
     SET LEIDA = 1, FECHA_LECTURA = SYSDATE
   WHERE NOTIF_ID = p_NOTIF_ID
     AND USUARIO_DESTINO_ID = p_USUARIO_ID
     AND CODIGO_EMPRESA = p_CODIGO_EMPRESA;
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_DASH_SUMMARY (
  p_FECHA_DESDE IN DATE,
  p_FECHA_HASTA IN DATE,
  p_CODIGO_EMPRESA IN NUMBER,
  p_ResultSet OUT SYS_REFCURSOR,
  p_Message OUT VARCHAR2
) AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT COUNT(1) TOTAL_TICKETS,
           SUM(CASE WHEN e.ES_FINAL = 0 THEN 1 ELSE 0 END) TICKETS_ABIERTOS,
           SUM(CASE WHEN UPPER(e.NOMBRE) = 'CERRADO' THEN 1 ELSE 0 END) TICKETS_CERRADOS,
           SUM(CASE WHEN UPPER(p.NOMBRE) = 'CRITICA' THEN 1 ELSE 0 END) TICKETS_CRITICOS,
           SUM(CASE WHEN e.ES_FINAL = 0 AND t.FECHA_VENCIMIENTO_SLA < SYSDATE THEN 1 ELSE 0 END) TICKETS_VENCIDOS,
           SUM(CASE WHEN t.USUARIO_RESPONSABLE_ID IS NULL THEN 1 ELSE 0 END) TICKETS_SIN_ASIGNAR,
           ROUND(NVL(AVG(CASE WHEN t.FECHA_RESOLUCION IS NOT NULL THEN t.FECHA_RESOLUCION - t.FECHA_CREACION END), 0), 4) TIEMPO_PROMEDIO_RESOLUCION
      FROM SOP_TICKET t
      JOIN SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
      JOIN SOP_PRIORIDAD p ON p.PRIORIDAD_ID = t.PRIORIDAD_ID
     WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
       AND (p_FECHA_DESDE IS NULL OR TRUNC(t.FECHA_CREACION) >= TRUNC(p_FECHA_DESDE))
       AND (p_FECHA_HASTA IS NULL OR TRUNC(t.FECHA_CREACION) <= TRUNC(p_FECHA_HASTA));
  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_Message := SQLERRM;
END;
/

CREATE OR REPLACE PROCEDURE SP_SOP_SLA_NOTIF (
  p_CODIGO_EMPRESA IN NUMBER,
  p_NOTIF_COUNT_OUT OUT NUMBER,
  p_Message OUT VARCHAR2
) AS
BEGIN
  INSERT INTO SOP_TICKET_NOTIF
    (NOTIF_ID, CODIGO_EMPRESA, TICKET_ID, USUARIO_DESTINO_ID, TIPO_DESTINO, EVENTO, TITULO, MENSAJE, CANAL)
  SELECT SEQ_SOP_NOTIF.NEXTVAL, t.CODIGO_EMPRESA, t.TICKET_ID, destino.USUARIO_ID,
         destino.TIPO_DESTINO, 'VENCIDO', 'Ticket vencido',
         'El ticket ' || t.TICKET_NUMERO || ' vencio por SLA.', 'INTERNA'
    FROM SOP_TICKET t
    JOIN SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
    JOIN (
      SELECT TICKET_ID, USUARIO_SOLICITANTE_ID USUARIO_ID, 'SOLICITANTE' TIPO_DESTINO
        FROM SOP_TICKET
       WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
      UNION
      SELECT TICKET_ID, USUARIO_RESPONSABLE_ID USUARIO_ID, 'RESPONSABLE' TIPO_DESTINO
        FROM SOP_TICKET
       WHERE CODIGO_EMPRESA = p_CODIGO_EMPRESA
    ) destino ON destino.TICKET_ID = t.TICKET_ID
   WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND destino.USUARIO_ID IS NOT NULL
     AND NVL(e.ES_FINAL, 0) = 0
     AND t.FECHA_VENCIMIENTO_SLA IS NOT NULL
     AND t.FECHA_VENCIMIENTO_SLA < SYSDATE
     AND NOT EXISTS (
       SELECT 1
         FROM SOP_TICKET_NOTIF n
        WHERE n.CODIGO_EMPRESA = t.CODIGO_EMPRESA
          AND n.TICKET_ID = t.TICKET_ID
          AND n.USUARIO_DESTINO_ID = destino.USUARIO_ID
          AND n.EVENTO = 'VENCIDO'
     );

  p_NOTIF_COUNT_OUT := SQL%ROWCOUNT;

  INSERT INTO SIS_EMAIL_QUEUE (
    EMAIL_ID, CODIGO_EMPRESA, MODULO_ORIGEN, REFERENCIA_ID, TO_EMAIL,
    TO_NAME, SUBJECT, BODY_HTML, BODY_TEXT, FECHA_PROGRAMADA
  )
  SELECT SEQ_EMAIL_Q.NEXTVAL, t.CODIGO_EMPRESA, 'SOPORTE', t.TICKET_ID,
         u.EMAIL, u.USUARIO, 'Ticket vencido por SLA',
         '<p>El ticket ' || t.TICKET_NUMERO || ' vencio por SLA.</p>',
         'El ticket ' || t.TICKET_NUMERO || ' vencio por SLA.',
         SYSDATE
    FROM SOP_TICKET t
    JOIN SOP_ESTADO e ON e.ESTADO_ID = t.ESTADO_ID
    JOIN SIS_USUARIOS u ON u.CODIGO_EMPRESA = t.CODIGO_EMPRESA
   WHERE t.CODIGO_EMPRESA = p_CODIGO_EMPRESA
     AND u.CODIGO_USUARIO IN (t.USUARIO_SOLICITANTE_ID, t.USUARIO_RESPONSABLE_ID)
     AND NVL(e.ES_FINAL, 0) = 0
     AND t.FECHA_VENCIMIENTO_SLA IS NOT NULL
     AND t.FECHA_VENCIMIENTO_SLA < SYSDATE
     AND NVL(u.RECIBE_EMAIL, 1) = 1
     AND u.EMAIL IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
         FROM SIS_EMAIL_QUEUE q
        WHERE q.CODIGO_EMPRESA = t.CODIGO_EMPRESA
          AND q.MODULO_ORIGEN = 'SOPORTE'
          AND q.REFERENCIA_ID = t.TICKET_ID
          AND q.TO_EMAIL = u.EMAIL
          AND q.SUBJECT = 'Ticket vencido por SLA'
     );

  p_Message := 'Success';
EXCEPTION
  WHEN OTHERS THEN
    p_NOTIF_COUNT_OUT := 0;
    p_Message := SQLERRM;
END;
/
