CREATE OR REPLACE PROCEDURE SP_CAT_DIF_GET_INM
(p_CodigoInmueble IN NUMBER, p_CodigoContribuyente IN NUMBER,
 p_CodigoEmpresa IN NUMBER, p_ResultSet OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT DESDE, HASTA, AFORO_B_T, AFORO_ANT, CODIGO_BENEFICIO,
           VP, APLICADO, ALICUOTA
      FROM CAT_CALCULO_DIFERENCIAS
     WHERE CODIGO_INMUEBLE = p_CodigoInmueble
       AND CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
       AND CODIGO_EMPRESA = p_CodigoEmpresa
     ORDER BY DESDE DESC, HASTA DESC;
END SP_CAT_DIF_GET_INM;
/
