CREATE OR REPLACE PROCEDURE SP_RM_MOV_GET_INM
(p_CodigoInmueble IN NUMBER, p_CodigoContribuyente IN NUMBER,
 p_CodigoEmpresa IN NUMBER, p_ResultSet OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN p_ResultSet FOR
    SELECT CODIGO_MOV_RAMO, CODIGO_CONCEPTO, EXTRA_CONCEPTO,
           NUMERO_DOCUMENTO, FECHA_MOV, MONTO_MOV, FECHA_PERIODO_INI,
           FECHA_PERIODO_FIN, APLICADO_ID, ESTATUS, MONTO_RECARGOS,
           MONTO_INTERESES, MONTO_EXTRA
      FROM RM_MOV_RAMOS
     WHERE CODIGO_IDENTIFICADOR = p_CodigoInmueble
       AND CODIGO_CONTRIBUYENTE = p_CodigoContribuyente
       AND CODIGO_EMPRESA = p_CodigoEmpresa
       AND TRIBUTO = 1
     ORDER BY FECHA_MOV DESC, CODIGO_MOV_RAMO DESC;
END SP_RM_MOV_GET_INM;
/
