CREATE OR REPLACE PROCEDURE ADM.SP_REP_ORD_PAGO_GET (
    p_CodigoOrdenPago IN NUMBER,
    p_ResultSet       OUT SYS_REFCURSOR,
    p_Message         OUT VARCHAR2,
    p_TotalRecords    OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
      INTO p_TotalRecords
      FROM ADM.ADM_ORDEN_PAGO OP
     WHERE OP.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    OPEN p_ResultSet FOR
        SELECT
            OP.CODIGO_ORDEN_PAGO,
            OP.TITULO_REPORTE,
            NVL(TOP.DESCRIPCION, '') TIPO_ORDEN_PAGO,
            OP.NUMERO_ORDEN_PAGO,
            OP.FECHA_ORDEN_PAGO,
            NVL(CMP.NUMERO_COMPROMISO, OP.NUMERO_COMPROMISO) NUMERO_COMPROMISO,
            NVL(CMP.FECHA_COMPROMISO, OP.FECHA_COMPROMISO) FECHA_COMPROMISO,
            NVL(PR.NOMBRE_PROVEEDOR, '') NOMBRE_PROVEEDOR,
            TO_CHAR(PR.CEDULA) CEDULA_PROVEEDOR,
            NVL(PR.RIF, '') RIF_PROVEEDOR,
            NVL(BC.NOMBRE, '') NOMBRE_BENEFICIARIO,
            NVL(BC.APELLIDO, '') APELLIDO_BENEFICIARIO,
            NVL(BC.IDENTIFICACION, '') CEDULA_BENEFICIARIO,
            OP.FECHA_PLAZO_DESDE,
            OP.FECHA_PLAZO_HASTA,
            NVL(OP.MONTO_LETRAS, '') MONTO_LETRAS,
            NVL(FP.DESCRIPCION, '') FORMA_PAGO,
            NVL(OP.CANTIDAD_PAGO, 0) CANTIDAD_PAGO,
            NVL(OP.MOTIVO, '') MOTIVO,
            NVL(OP.STATUS, '') STATUS
          FROM ADM.ADM_ORDEN_PAGO OP
          LEFT JOIN ADM.ADM_DESCRIPTIVAS TOP
            ON TOP.DESCRIPCION_ID = OP.TIPO_ORDEN_PAGO_ID
          LEFT JOIN ADM.ADM_DESCRIPTIVAS FP
            ON FP.DESCRIPCION_ID = OP.FRECUENCIA_PAGO_ID
          LEFT JOIN ADM.ADM_PROVEEDORES PR
            ON PR.CODIGO_PROVEEDOR = OP.CODIGO_PROVEEDOR
          LEFT JOIN ADM.ADM_CONTACTO_PROVEEDOR BC
            ON BC.CODIGO_PROVEEDOR = OP.CODIGO_PROVEEDOR
           AND BC.PRINCIPAL = 1
          LEFT JOIN (
                SELECT
                    COP.CODIGO_ORDEN_PAGO,
                    MAX(PC.NUMERO_COMPROMISO) NUMERO_COMPROMISO,
                    MAX(PC.FECHA_COMPROMISO) FECHA_COMPROMISO
                  FROM ADM.ADM_COMPROMISO_OP COP
                  LEFT JOIN PRE.PRE_COMPROMISOS PC
                    ON PC.CODIGO_COMPROMISO = COP.CODIGO_IDENTIFICADOR
                 GROUP BY COP.CODIGO_ORDEN_PAGO
          ) CMP
            ON CMP.CODIGO_ORDEN_PAGO = OP.CODIGO_ORDEN_PAGO
         WHERE OP.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    p_Message := 'Success';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
        p_TotalRecords := 0;
        OPEN p_ResultSet FOR
            SELECT
                CAST(NULL AS NUMBER) CODIGO_ORDEN_PAGO,
                CAST(NULL AS VARCHAR2(4000)) TITULO_REPORTE,
                CAST(NULL AS VARCHAR2(4000)) TIPO_ORDEN_PAGO,
                CAST(NULL AS VARCHAR2(100)) NUMERO_ORDEN_PAGO,
                CAST(NULL AS DATE) FECHA_ORDEN_PAGO,
                CAST(NULL AS VARCHAR2(100)) NUMERO_COMPROMISO,
                CAST(NULL AS DATE) FECHA_COMPROMISO,
                CAST(NULL AS VARCHAR2(4000)) NOMBRE_PROVEEDOR,
                CAST(NULL AS VARCHAR2(100)) CEDULA_PROVEEDOR,
                CAST(NULL AS VARCHAR2(100)) RIF_PROVEEDOR,
                CAST(NULL AS VARCHAR2(4000)) NOMBRE_BENEFICIARIO,
                CAST(NULL AS VARCHAR2(4000)) APELLIDO_BENEFICIARIO,
                CAST(NULL AS VARCHAR2(100)) CEDULA_BENEFICIARIO,
                CAST(NULL AS DATE) FECHA_PLAZO_DESDE,
                CAST(NULL AS DATE) FECHA_PLAZO_HASTA,
                CAST(NULL AS VARCHAR2(4000)) MONTO_LETRAS,
                CAST(NULL AS VARCHAR2(4000)) FORMA_PAGO,
                CAST(NULL AS NUMBER) CANTIDAD_PAGO,
                CAST(NULL AS VARCHAR2(4000)) MOTIVO,
                CAST(NULL AS VARCHAR2(10)) STATUS
              FROM DUAL
             WHERE 1 = 0;
END SP_REP_ORD_PAGO_GET;
/
