CREATE OR REPLACE PROCEDURE ADM.SP_REP_RET_ISLR_DOC_GET (
    p_CodigoOrdenPago IN NUMBER,
    p_ResultSet       OUT SYS_REFCURSOR,
    p_Message         OUT VARCHAR2,
    p_TotalRecords    OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
      INTO p_TotalRecords
      FROM ADM.ADM_DOCUMENTOS_OP DOC
      JOIN ADM.ADM_IMPUESTOS_DOCUMENTOS_OP IMP
        ON IMP.CODIGO_DOCUMENTO_OP = DOC.CODIGO_DOCUMENTO_OP
      JOIN ADM.ADM_DESCRIPTIVAS DES
        ON DES.DESCRIPCION_ID = IMP.TIPO_RETENCION_ID
       AND DES.CODIGO = 'ISLR'
     WHERE DOC.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    OPEN p_ResultSet FOR
        SELECT
            NVL(DOC.NUMERO_DOCUMENTO, '') NUMERO_FACTURA,
            DOC.FECHA_DOCUMENTO FECHA_FACTURA,
            NVL(RET.CONCEPTO_PAGO, '') CONCEPTO_PAGO,
            NVL(IMP.MONTO_IMPUESTO_EXENTO, 0) IMPUESTO_EXENTO,
            NVL(IMP.BASE_IMPONIBLE, 0) BASE_IMPONIBLE,
            TO_CHAR(NVL(RET.POR_RETENCION, 0), 'FM999999990D00') ALICUOTA,
            NVL(IMP.MONTO_IMPUESTO, 0) ISLR_RETENIDO,
            0 SUSTRAENDO
          FROM ADM.ADM_DOCUMENTOS_OP DOC
          JOIN ADM.ADM_IMPUESTOS_DOCUMENTOS_OP IMP
            ON IMP.CODIGO_DOCUMENTO_OP = DOC.CODIGO_DOCUMENTO_OP
          JOIN ADM.ADM_DESCRIPTIVAS DES
            ON DES.DESCRIPCION_ID = IMP.TIPO_RETENCION_ID
           AND DES.CODIGO = 'ISLR'
          LEFT JOIN ADM.ADM_RETENCIONES RET
            ON RET.CODIGO_RETENCION = IMP.CODIGO_RETENCION
         WHERE DOC.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago
         ORDER BY DOC.CODIGO_DOCUMENTO_OP, IMP.CODIGO_IMPUESTO_DOCUMENTO_OP;

    p_Message := 'Success';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
        p_TotalRecords := 0;
        OPEN p_ResultSet FOR
            SELECT
                CAST(NULL AS VARCHAR2(100)) NUMERO_FACTURA,
                CAST(NULL AS DATE) FECHA_FACTURA,
                CAST(NULL AS VARCHAR2(4000)) CONCEPTO_PAGO,
                CAST(NULL AS NUMBER) IMPUESTO_EXENTO,
                CAST(NULL AS NUMBER) BASE_IMPONIBLE,
                CAST(NULL AS VARCHAR2(100)) ALICUOTA,
                CAST(NULL AS NUMBER) ISLR_RETENIDO,
                CAST(NULL AS NUMBER) SUSTRAENDO
              FROM DUAL
             WHERE 1 = 0;
END SP_REP_RET_ISLR_DOC_GET;
/
