CREATE OR REPLACE PROCEDURE ADM.SP_REP_RET_ISLR_GET (
    p_CodigoOrdenPago IN NUMBER,
    p_ResultSet       OUT SYS_REFCURSOR,
    p_Message         OUT VARCHAR2,
    p_TotalRecords    OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
      INTO p_TotalRecords
      FROM ADM.ADM_ORDEN_PAGO OP
     WHERE OP.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    OPEN p_ResultSet FOR
        SELECT
            OP.CODIGO_ORDEN_PAGO,
            OP.NUMERO_ORDEN_PAGO,
            OP.FECHA_INS FECHA,
            NVL(OP.NOMBRE_AGENTE_RETENCION, '') NOMBRE_AGENTE_RETENCION,
            NVL(OP.TELEFONO_AGENTE_RETENCION, '') TELEFONO_AGENTE_RETENCION,
            NVL(OP.RIF_AGENTE_RETENCION, '') RIF_AGENTE_RETENCION,
            NVL(OP.DIRECCION_AGENTE_RETENCION, '') DIRECCION_AGENTE_RETENCION,
            NVL(PR.NOMBRE_PROVEEDOR, '') NOMBRE_SUJETO_RETENIDO,
            NVL(PR.RIF, '') RIF_SUJETO_RETENIDO,
            NVL(OP.STATUS, '') STATUS
          FROM ADM.ADM_ORDEN_PAGO OP
          LEFT JOIN ADM.ADM_PROVEEDORES PR
            ON PR.CODIGO_PROVEEDOR = OP.CODIGO_PROVEEDOR
         WHERE OP.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    p_Message := 'Success';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
        p_TotalRecords := 0;
        OPEN p_ResultSet FOR
            SELECT
                CAST(NULL AS NUMBER) CODIGO_ORDEN_PAGO,
                CAST(NULL AS VARCHAR2(100)) NUMERO_ORDEN_PAGO,
                CAST(NULL AS DATE) FECHA,
                CAST(NULL AS VARCHAR2(4000)) NOMBRE_AGENTE_RETENCION,
                CAST(NULL AS VARCHAR2(100)) TELEFONO_AGENTE_RETENCION,
                CAST(NULL AS VARCHAR2(100)) RIF_AGENTE_RETENCION,
                CAST(NULL AS VARCHAR2(4000)) DIRECCION_AGENTE_RETENCION,
                CAST(NULL AS VARCHAR2(4000)) NOMBRE_SUJETO_RETENIDO,
                CAST(NULL AS VARCHAR2(100)) RIF_SUJETO_RETENIDO,
                CAST(NULL AS VARCHAR2(10)) STATUS
              FROM DUAL
             WHERE 1 = 0;
END SP_REP_RET_ISLR_GET;
/
