CREATE OR REPLACE PROCEDURE ADM.SP_REP_TIM_FIS_GET (
    p_CodigoOrdenPago IN NUMBER,
    p_ResultSet       OUT SYS_REFCURSOR,
    p_Message         OUT VARCHAR2,
    p_TotalRecords    OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
      INTO p_TotalRecords
      FROM ADM.ADM_ORDEN_PAGO OP
     WHERE OP.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    OPEN p_ResultSet FOR
        SELECT
            OP.CODIGO_ORDEN_PAGO,
            NVL(OP.NUMERO_ORDEN_PAGO, '') NUMERO_ORDEN_PAGO,
            NVL(OP.NOMBRE_AGENTE_RETENCION, '') NOMBRE_AGENTE_RETENCION,
            NVL(OP.RIF_AGENTE_RETENCION, '') RIF_AGENTE_RETENCION,
            NVL(PR.NOMBRE_PROVEEDOR, '') NOMBRE_CONTRIBUYENTE,
            NVL(PR.RIF, '') RIF_CONTRIBUYENTE,
            NVL(OP.MOTIVO, '') MOTIVO,
            NVL(OP.STATUS, '') STATUS,
            NVL(LT.BASE_IMPONIBLE, 0) BASE_IMPONIBLE,
            NVL(LT.MONTO_RETENCION, 0) MONTO_RETENCION
          FROM ADM.ADM_ORDEN_PAGO OP
          LEFT JOIN ADM.ADM_PROVEEDORES PR
            ON PR.CODIGO_PROVEEDOR = OP.CODIGO_PROVEEDOR
          LEFT JOIN (
                SELECT
                    RET.CODIGO_ORDEN_PAGO,
                    MAX(RET.BASE_IMPONIBLE) BASE_IMPONIBLE,
                    MAX(RET.MONTO_RETENCION) MONTO_RETENCION
                  FROM ADM.ADM_RETENCIONES_OP RET
                  JOIN ADM.ADM_DESCRIPTIVAS DES
                    ON DES.DESCRIPCION_ID = RET.TIPO_RETENCION_ID
                   AND DES.CODIGO = 'LT'
                 GROUP BY RET.CODIGO_ORDEN_PAGO
          ) LT
            ON LT.CODIGO_ORDEN_PAGO = OP.CODIGO_ORDEN_PAGO
         WHERE OP.CODIGO_ORDEN_PAGO = p_CodigoOrdenPago;

    p_Message := 'Success';
EXCEPTION
    WHEN OTHERS THEN
        p_Message := SUBSTR(SQLERRM, 1, 4000);
        p_TotalRecords := 0;
        OPEN p_ResultSet FOR
            SELECT
                CAST(NULL AS NUMBER) CODIGO_ORDEN_PAGO,
                CAST(NULL AS VARCHAR2(100)) NUMERO_ORDEN_PAGO,
                CAST(NULL AS VARCHAR2(4000)) NOMBRE_AGENTE_RETENCION,
                CAST(NULL AS VARCHAR2(100)) RIF_AGENTE_RETENCION,
                CAST(NULL AS VARCHAR2(4000)) NOMBRE_CONTRIBUYENTE,
                CAST(NULL AS VARCHAR2(100)) RIF_CONTRIBUYENTE,
                CAST(NULL AS VARCHAR2(4000)) MOTIVO,
                CAST(NULL AS VARCHAR2(10)) STATUS,
                CAST(NULL AS NUMBER) BASE_IMPONIBLE,
                CAST(NULL AS NUMBER) MONTO_RETENCION
              FROM DUAL
             WHERE 1 = 0;
END SP_REP_TIM_FIS_GET;
/
