CREATE OR REPLACE PROCEDURE SIS.SP_REP_AGT_RET_GET (
    p_CodigoEmpresa IN NUMBER,
    p_ResultSet     OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_ResultSet FOR
        SELECT
            NVL(EMP.NOMBRE_EMPRESA, '') NOMBRE_AGENTE_RETENCION,
            NVL(DES.CODIGO_DESCRIPCION, '')
                || NVL(EMP.NUMERO_IDENTIFICACION, '') RIF_AGENTE_RETENCION
          FROM SIS.SIS_EMPRESAS EMP
          LEFT JOIN SIS.SIS_DESCRIPTIVAS DES
            ON DES.DESCRIPCION_ID = EMP.IDENTIFICACION_ID
         WHERE EMP.CODIGO_EMPRESA = p_CodigoEmpresa;
END SP_REP_AGT_RET_GET;
/
